go.mod, go.sum, pkg/redis/mocks/Client.go, pkg/redis/redis_client.go, pkg/redis/redis_client_test.go, pkg/redis/redis_factory.go
I noticed that upon certain redis errors (e.g. when the redis server crashes due to OOM), the producers do not notice it and messages get dropped.
In this pull request, I added an exponential backoff to mitigate the impact.
=> add exponential backoff to redis client

pkg/apiserver/sql/query_builder.go, pkg/apiserver/sql/query_builder_test.go
The current version of the list/sql query builder does not properly handle "is null" or similar comparisons based on "is"/"is not". Hence, I added the capabilities to the query builder.
=> add handling of is/is not during query building

pkg/kvstore/ddb.go
The current implementation of the key value store can't be used with dynamodb since the annotation changed from dynamodb to ddb and "key,hash" to "key=hash".
=> Fixed Key/Value store integration for dynamodb

pkg/currency/service_test.go, pkg/currency/updater.go, pkg/http/client.go, pkg/http/client_test.go, pkg/http/mocks/Client.go, pkg/http/request.go, pkg/http/request_test.go, pkg/oauth2/google.go, pkg/oauth2/google_test.go
This MR addresses two problems:
- If you start an HTTP request and your context is canceled in the meantime, gosoline logs an error (i.e., a sentry message) and returns a wrapped error to the caller. Instead, we will now not log the error (which is the responsibility of the caller in the case of a canceled context) and return the original cancellation error (thus the caller can easily compare this to context.Canceled and handle it accordingly).
- If you create a request with http.NewRequest() it would use the default resty client instead of the client later used to perform the request. Thus, the settings for timeout and retries had no effect. This is a breaking change as it requires the caller to use pass the client in http.NewRequest(client). Passing nil is supported to get the old …
=> Use the correct client in a request and handle context cancellation 

pkg/ddb/repository.go, pkg/stream/input_configurable.go, pkg/stream/input_sns.go, pkg/stream/input_sqs.go
add config option `runner_count` to stream sqs input to run multiple sqs receive actions simultaneously
=> stream: parallize sqs input readers;

pkg/apiserver/handler.go, pkg/apiserver/middleware_logger.go
the apiserver logger middleware should log a request as error level if there is an error during handling the request instead of in the info level
=> apiserver: log api errors;

pkg/redis/redis_client.go
The current setting creates an initial backoff interval of 10^12 seconds. I suggest switching to an integer based configuration, and just assume the given values to be in seconds.
=> redis: use integer config values for backoff;

pkg/apiserver/crud/crud_test.go, pkg/apiserver/sql/query_builder.go, pkg/apiserver/sql/query_builder_test.go, pkg/db-repo/metadata.go
If you now query for `foo != null`, you will get some results instead of nothing at all.
=> db-repo, sql: added ability to treat nulls like in go instead of like in sql;

pkg/mon/metric_daemon.go, pkg/mon/metric_writer_daemon.go
there is a race condition during application boot if multiple modules add default metrics  
this should be prevented by locking the `AddDefault` function
=> mon: lock metric daemon while adding default metrics;

pkg/parquet/reader.go, pkg/parquet/schema.go
Fix writing timestamps, use the same format as AWS firehose
=> parquet: write time.Time like firehose;

pkg/mon/logger.go, pkg/mon/logger_options.go, pkg/mon/logger_test.go
In the past, we would only store a reference to maps passed into
our logger with WithFields, WithContext, a context resolver or any
other means. As we needed to transform the errors to strings for
them to appear in the json encoded message, we replaced the value
in the map directly. However, this caused concurrent reads and writes
to the map to happen if more than one thread was using the same map.
We later started to take a copy of the map, so we were a lot less likely
to run into a concurrent read and write. Still, we did not account for
nested maps and objects, so a concurrent read and write panic could
still happen.
The new solution is to perform a deep clone of any maps, structs or
arrays (basically anything meaningful represented by a pointer) and
avoid writing anything into the …
=> logger: copy fields and structs passed into the logger deeply;

pkg/mon/logger.go, pkg/mon/logger_test.go
currently if we try to log a field of type `time.Time` an empty object is logged instead.
Expected behavior: allow `time.Time` fields to be logged.
=> mon: logger support time.Time fields

pkg/fixtures/loader.go, pkg/fixtures/module.go, pkg/fixtures/writer_ddb.go, pkg/fixtures/writer_ddb_kv.go, pkg/fixtures/writer_mysql.go, test/fixtures_dynamodb_test.go, test/fixtures_mysql_test.go
**Motivation:**
For some use cases, for example in tests, I just want to load some fixtures in a synchronous way and I do not need to use the module/application/kernel abstraction for that.
In those cases you can just create the `FixtureLoader` directly and call the `Load` method.
=> fixtures: separate loader from module;

pkg/fixtures/writer_ddb.go, test/fixtures_dynamodb_test.go
This is needed to be able to create global secondary indexes.
=> fixtures: allow to include global settings for ddb writer;

pkg/blob/store.go, pkg/ddb/expr_projection.go, pkg/ddb/metadata_factory.go, pkg/ddb/metadata_factory_test.go
If you are using a real (no localstack) endpoint for S3 and use
autoCreate, S3 might return an error telling you the bucket does already
exist. We handled this in the past (failing to create a bucket because
it already exsits is not really an error, especially in the context of
autoCreate), but S3 can return a second error telling you you already
own the bucket instead. As this is basically the same situation, also
ignore that error.
For ddb, if we automatically generate the table, we have to strip any
json tags, otherwise a line like 'Foo string `json:"foo,omitempty"`'
would try to create a field called "foo,omitempty" instead of foo. This
then breakes if the the field is used for any keys because it can later
not be found (because you only reference foo instead of foo,omitempty).
=> blob, ddb: avoid error log on existing bucket and strip out additional json arguments;

examples/gosoline-fixture-loading/main.go, pkg/fixtures/loader_noop.go, pkg/fixtures/writer_ddb_kvstore.go, pkg/fixtures/writer_mysql_orm.go, pkg/fixtures/writer_mysql_plain.go, pkg/fixtures/writer_redis.go, pkg/fixtures/writer_redis_kvstore.go, test/fixtures_mysql_test.go
**Summary:**
- Cleanup unnecessary pointer to slice. See [use case for pointer to slices](https://medium.com/swlh/golang-tips-why-pointers-to-slices-are-useful-and-how-ignoring-them-can-lead-to-tricky-bugs-cac90f72e77b).
- Cleanup redundant type assertion check. The default behavior is panicking and producing a better error message.
- Add a log message to the noop fixture loader (useful when running tests).
=> fixtures: cleanup pointer to slice;

pkg/stream/output_file.go
**Steps to reproduce:**
Write a unit test and write different values to the file output in a loop (500 times should be enough). 
At some point in the iteration, it will not completely truncate the contents of the file (it looks like it wrote too much).
This issue was causing some integration tests to flap (failing 1 every 20 runs).
**Solution:**
Add an explicit flag when opening the file to make sure it is truncated.
=> stream: fix file output writing too much;

pkg/test/component_cloudwatch.go, pkg/test/component_dynamodb.go, pkg/test/component_elasticsearch.go, pkg/test/component_kinesis.go, pkg/test/component_mysql.go, pkg/test/component_redis.go, pkg/test/component_sns_sqs.go, pkg/test/component_wiremock.go, pkg/test/docker.go, pkg/test/test.go, test/test_configs/config.mysql.test.yml
**Summary:**
* In some cases, the tests are not cleaning up the docker containers they started. 
* This causes problems when trying to run the tests again (locally or on a CI environment).
* Set the default expiration period to 1 minute (was previously 1 hour)
* Make it configurable so that it can be adapted if needed e.g. for long-running tests for example.
* Add more logging to investigate failing tests due to docker problems in the CI.
=> test: make docker expiration period configurable;

pkg/stream/multi_producer.go, pkg/stream/multi_producer_test.go
Adds a multi producer that send input to multiple streams. Based on [io.MultiWriter ](https://golang.org/pkg/io/#MultiWriter)
=> stream: added multi producer based on std lib multiwriter

pkg/cloud/error.go, pkg/cloud/error_test.go, pkg/cloud/request.go, pkg/currency/service.go, pkg/sqs/queue.go
Sadly in the current state it is quite hard to see whether an error was
the result of a context getting canceled. For now we moved all the logic
to detect this into a single function handling AWS errors, our own
canceled context error as well as multierrors containing canceled
contexts. A user of the library can thus easily use our function to
check whether the error could be handled in any way besides stopping
processing as fast as possible.
=> cloud: improved support to detected canceled context errors;

pkg/test/component_cloudwatch.go, pkg/test/component_dynamodb.go, pkg/test/component_elasticsearch.go, pkg/test/component_kinesis.go, pkg/test/component_mysql.go, pkg/test/component_redis.go, pkg/test/component_sns_sqs.go, pkg/test/component_wiremock.go, pkg/test/docker.go, pkg/test/mocks_hosts.go, pkg/test/test.go, test/component_wiremock_test.go, test/es/config-v6.test.yml, test/es/config-v7.test.yml, test/fixtures_dynamodb_test.go, test/fixtures_mysql_test.go, test/fixtures_redis_test.go, test/test_configs/config.cloudwatch.test.yml, test/test_configs/config.dynamodb.test.yml, test/test_configs/config.elasticsearch.test.yml, test/test_configs/config.fixtures_mysql.test.yml, test/test_configs/config.kinesis.test.yml, test/test_configs/config.mysql.test.yml, test/test_configs/config.redis.test.yml, test/test_configs/config.sns_sqs.test.yml, test/test_configs/config.wiremock.test.yml
Closes #225 
In an ideal world, we would always use localhost for Docker-based tests. 
But this is not the case:
- In CI we use docker-in-docker (dind), so we cannot use localhost. We can use either the container ip or the gateway ip for the Bridge network.
- For Mac users this approach does not work. They should use localhost or create a network alias to support the gateway ip adress.
To simplify the usage of the tests package we take care of it, check which address is reacheable and provide the host via `mock.ProvideXxxPort()` methods.
=> test: provide hostname mapping;

pkg/db/client.go
`QueryRow` implementation was broken and the errors were just being ignored.
=> db: fix client error in QueryRow;

pkg/coffin/coffin.go, pkg/coffin/coffin_test.go, pkg/kernel/kernel_test.go
A tomb contains a mutex which again may not be copied after it is
first used. If we copy a tomb we copy the mutex. However, if we got the
tomb from tomb.WithContext, another go routine already has a reference
to this tomb and thus will lock a different copy of the mutex than we
have stored in our coffin. Thus, if the tomb later tries to close the
dying channel the critical section of doing this might be entered twice
at the same time, causing a panic because we are closing a closed
channel.
=> coffin: refactored coffin type to contain a pointer to a tomb instead of a tomb;

.github/workflows/go.yml, pkg/apiserver/profiler.go, pkg/apiserver/server.go, pkg/apiserver/server_test.go, pkg/db-repo/repository_test.go, pkg/ddb/repository_test.go
We should always run `go vet` on our code to make sure we are not
introducing stupid mistakes (like copying a mutex, go vet actually saw
the bug we just fixed with coffin). Thus we now always run it on our
code (and now our code actually passes it).
=> apiserver: exposed AddProfilingEndpoints to stop skipping tests and added `go vet` to ci config;

pkg/db-repo/change_history.go, pkg/db-repo/change_history_manager.go, pkg/db-repo/change_history_metadata.go, pkg/db-repo/model.go, pkg/db/connection.go, pkg/test/component_mysql.go, test/db_repo_change_history_test.go, test/test_configs/config.db_repo_change_history.test.yml, test/test_fixtures/migrations_db_repo_change_history/1_migrations_tables.up.sql
**Summary:**
- Add a `db_repo.MigrateChangeHistory` function.
- The migration creates and updates a history table and a set of triggers.
- This has only been tested on mysql.
- Changed connection cache on `pkg/db/connection.go` to allow connections with different settings (integration tests were failing when running after each other).
**Open points:**
- It is not possible to get the change_author for delete operations with this approach.
- Need a way to prevent 2 applications to run the migration concurrently. (won't implement it in this iteration)
- Needs mysql option `log_bin_trust_function_creators=1`
=> db_repo: change history

pkg/kvstore/in_memory.go
Added a default ttl of 1 hour for backwards compatibility but not sure if it's necessary.
=> kvstore: In memory kvstore time to live fix

pkg/conc/ddb_lock_provider_test.go, pkg/stream/input_configurable.go, pkg/stream/input_sns.go
This if needed if you consider the following setup:
Project: awesome-project
Family: your-awesome-family
Env: production
Application: this-is-your-application
And now you want to create a queue for MonitoringEvent messages and get this name:
awesome-project-production-your-awesome-family-this-is-your-application-MonitoringEvent
Oh no, this is now 7 characters too long for the SQS queue name limit of
80 characters! So you shorten the name of application for this queue to "app":
awesome-project-production-your-awesome-family-app-MonitoringEvent
And now you only have 66 characters which is way below the 80 character limit.
=> Make sqs queue application configurable

pkg/application/app.go, pkg/application/app_test.go, pkg/application/testdata/config.dist.yml
If you have a key like `redis.your-component.address`, we need to map
the environment variable `REDIS_YOUR_COMPONENT_ADDRESS` to it. The dash
was not replaced before and thus you would have needed to set
`REDIS_YOUR-COMPONENT_ADDRESS`.
=> application: added replacement of - to _ in env key replacer;

pkg/stream/input_configurable.go, pkg/stream/input_sns.go, pkg/stream/input_sqs.go, pkg/stream/input_sqs_test.go, pkg/stream/unmarshal.go
Not all stream messages have the message format. Added a configuration mechanism to the unmarshalling of stream inputs.
=> stream: configure unmarshall

go.sum, pkg/http/client.go
In some cases its important to read the response Header.
Not sure if we should wrap the `net/http Header`
=> http: response should include the header

pkg/mon/logger_context_enforce.go, pkg/mon/logger_context_enforce_test.go
In the past, the ContextEnforcingLogger would happily catch errors like
h.logger.Info(), but it failed on h.logger.WithFields(...).Info(). The
reason was that WithFields would go to the embedded logger interface and
invoke *mon.Logger.WithFields which would return a plain *mon.logger. We
now catch these cases and return a wrapped logger again. For WithContext
we can actually drop our context check as we now know the logger is
using a context.
=> mon: added WithChannel, WithContext and WithFields to ContextEnforcingLogger;

pkg/ddb/repository.go, test/conc/ddb_lock_test.go, test/ddb/ddb_test.go
This commit fixes a small bug which would ignore the settings in
ddb.backoff because we swapped the two arguments to cfg.Merge by
accident.
=> ddb: use the backoff settings configured in config.dist.yml;

pkg/ddb/metadata_factory.go, pkg/ddb/metadata_factory_test.go
Suppose you have a struct like this:
type MyStruct struct {
Field string `json:"field,omitempty" ddb:"global=hash"`
}
Previously gosoline would think the json tag for Field would be
"field,omitempty". This is however not what the programmer intended and
thus needs to resolve to "field" instead. Therefore this commit changes
the way we parse these tags to account for these kinds of tags.
=> ddb: fix parsing of json tags for ddb key and hash fields;

pkg/cloud/error.go, pkg/cloud/request.go
In the past we tried to detect certain (network) on our own. As go now
features errors.Is() and errors.As(), we can simplify this code a lot
and improve the error detection rate a little bit at the same time.
=> cloud: refactored error handling such that we more easily detect a broader range of errors;

pkg/apiserver/auth/token_bearer.go, pkg/apiserver/auth/token_bearer_test.go, pkg/kvstore/batch.go, pkg/kvstore/chain.go, pkg/kvstore/chain_test.go, pkg/kvstore/ddb.go, pkg/kvstore/ddb_test.go, pkg/kvstore/empty.go, pkg/kvstore/in_memory.go, pkg/kvstore/kvstore.go, pkg/kvstore/redis.go, pkg/kvstore/redis_test.go, pkg/kvstore/uniq.go, pkg/kvstore/uniq_test.go
In the past, we would return that a value is not missing should the
missingCache contain it and instead return write an empty value to the
out parameter. However, this proved to be a mistake as you would now
have to check whether something was found and whether that something was
actually a valid value. Instead, we now transparently return "nothing
was found" should the cache tell us that we don't need to check for the
value, so there is no difference on the API anymore whether missing
value caching is enabled or not.
=> kvstore: refactored error handling and made chain store return useful results if you are caching missing values;

pkg/parquet/partitioner.go, pkg/parquet/partitioner_test.go
You can now specify how large a partition may grow before getting
flushed as well as how the day is divided into partitions. Previously,
only the interval in which partitions got written was specified and also
served as the division of the day into partitions. So if you had your
interval set to 15min and got an event for 8am and 2pm, they ended up in
separate partitions and were then flushed around 15 minutes later. Now
you could for example put a whole day into the same partition and still
write out every 15 minutes, so the two events would end up in the same
partition.
=> parquet: added two more dimensions to configure the partitioner;

pkg/apiserver/handler.go
Add a handler for multipart forms.
To handle optional file uploads, I had to catch the ErrMissingFile and ignore it. If you have strong feelings about this, let's talk.
=> [api]: enable multipart form with optional file

pkg/ddb/repository.go
When passing an entity struct with all values filled to repository.BatchDeleteItems, then you get an error as the request is only expecting the keys.
I added the transformation of the structs to their respective keys.
=> ddb: allow passing of whole entities to BatchDeleteItems;

pkg/cloud/aws_clients_test.go, pkg/mon/logger.go, pkg/mon/logger_context_enforce.go, pkg/mon/logger_sampling.go, pkg/mon/mocks/Logger.go, pkg/tracing/context_missing.go, pkg/tracing/message_encode_handler_test.go, pkg/tracing/trace_id_invalid_strategy.go
WithFields used to accept any map[string]interface{}, but was almost
always called with mon.Fields instead. While the two types are
compatible and client code should not be affected, tests who check what
gets logged are. In those you were in the awkward situation that you
passed mon.Fields in your code under test, but the mock needed to listen
for map[string]interface{}, or it would not match. This is no longer the
case.
=> mon: replace WithFields(MSI) with WithFields(Fields);

pkg/clock/ticker.go, pkg/clock/ticker_test.go
This adds an improved ticker compared to the default ticker of go.
Instead of just ticking, it can also be reset, meaning the next tick
occurs only after the whole duration again. We are already using this
pattern in quite some places, but mostly with replacing the ticker
itself. Instead, you now can just call Ticker.Reset (which is even
thread-safe).
=> clock: added ticker implementation;

pkg/db/connection.go
This should help against `connect: cannot assign requested address`. Please refer to:
http://techblog.en.klab-blogs.com/archives/31093990.html
and
http://dsas.blog.klab.org/archives/2018-02/configure-sql-db.html
=> db: added max idle conns and max open conns config option;

docs/framework/config.all.md, pkg/application/app.go, pkg/application/options.go, pkg/coffin/coffin.go, pkg/kernel/kernel.go, pkg/kernel/kernel_test.go, pkg/stream/consumer.go, pkg/stream/consumer_test.go, pkg/stream/producer.go, pkg/stream/producer_daemon.go, pkg/stream/producer_daemon_factory.go, pkg/stream/producer_daemon_test.go
this pr adds the possibility to add batching and aggregation of messages to the producer.  
by adding the following settings to the producer config:
```
producer:
event:
daemon:
enabled: true           // enables the asynchronous daemin
aggregation_size: 1 // how many messages to aggregate (1 means no aggregation)
batch_size: 10         // how many messages in a batch
buffer_size: 10         // buffer size of the internal channel
interval: 1m0s          // if batch_size not achieved in interval, send messages
runner_count: 10     // worker threads running which send the batches
```
you get a producer which doesn't send the message directly but instead uses a channel to push the message to a daemon, which can aggregate multiple message into one and then sends out these aggregated messages …
=> stream: producer daemon;

pkg/kvstore/configurable.go, pkg/kvstore/in_memory.go, pkg/kvstore/kvstore.go
This fixes #143 by allowing a user to specify different cache sizes etc.
than the defaults. If no or invalid values are specified the cache falls
back to the default values.
Closes #143.
=> kvstore: exposed inMemory configuration options to config file;

pkg/stream/input_configurable.go, pkg/stream/output_configurable.go, pkg/stream/producer_daemon.go, test/stream/config.dist.yml, test/stream/producer_daemon_test.go
When the kernel initiates a shutdown while there are queued messages, we
need to give at least a few seconds to write them to their output,
otherwise we immediately receive a context.Canceled error.
=> stream: allow a few seconds for the producer daemon to write its messages upon shutdown;

pkg/apiserver/server.go, pkg/apiserver/server_test.go, test/stream/config.dist.yml
track concurrent request count based on connection states instead of a http middleware
=> apiserver: concurrent request count metric

pkg/cloud/aws/executor.go, pkg/exec/error.go, pkg/redis/client_test.go, pkg/redis/exec.go
Redis returns `redis.Nil` as an error should no element be found. This
however confuses the executor as it thinks the command failed and needs
to be retried. Instead, we have to return nil to the executor and later
restore the error for the caller to ensure the use of the executor stays
invisible to the caller, but we don't retry requests we don't need to.
Also remove a rare crash in the aws executor should an error be returned.
=> redis: "hide" the error returned by redis if an element is not found from the executor;

pkg/apiserver/crud/create.go, pkg/apiserver/crud/crud_test.go, pkg/apiserver/crud/delete.go, pkg/apiserver/crud/update.go, pkg/apiserver/error.go, pkg/validation/error.go, pkg/validation/validator.go
Instead of returning a generic error with some special string we now
return a custom error type. This error is then detected by the
apiserver/crud code after a write to the database fails and returned as
a HTTP 400 response to the client instead of generating a HTTP 500 error
and logging an error.
=> apiserver/crud, validation: introduced own error type for validation failues and respond with HTTP 400 in case of a failure;

pkg/mon/error.go, pkg/mon/mocks/factory.go, pkg/stream/consumer_batch_test.go, pkg/stream/producer_daemon.go, pkg/stream/producer_daemon_test.go
mon/mocks: add common error detection to logger mock;
Added `NewLoggerMockedLevel` to allow specifying the maximum log level
you expect to be logged. A common use case is a test where a component
might normally swallow an error, but you need an easy way to ensure no
such error was thrown and logged by your test. Additionally the logger
mock now checks the format of the message and, if formatting marks are
detected, the use of Infof/Warnf/... is enforced. If no such marks are
detected, Info/Warn/... should be used instead.
stream: handle application termination in producer daemon;
Upon termination of the application, we start shutting down the producer
daemon and cancel all contexts. However, we have to delay cancling the
context used to write the message to the output (by one second by …
=> Logger mock refactor and producer daemon fix

README.md, pkg/cloud/aws/error.go, pkg/cloud/aws/error_test.go, pkg/cloud/aws/executor.go, pkg/ddb/repository.go, pkg/exec/error.go, pkg/exec/error_canceled.go, pkg/exec/error_canceled_test.go, pkg/exec/error_test.go, pkg/exec/executor_backoff.go, pkg/exec/executor_backoff_test.go, pkg/exec/test_http_client.go, pkg/redis/client_test.go, pkg/redis/exec.go
- improved logging to detect errors caused by reaching the configured max elapsed time threshold
- added error check for Client.Timeout exceeded while awaiting headers
- added error check for net/http: TLS handshake timeout
=> exec: improved logging, added error checks for header and tls timeout;

pkg/stream/pipeline.go
In an integration test you could easily have an input which quickly
finishes its `Run` method. With a little bit of bad luck your pipeline
has not yet started the read routine and therefore the coffin dies
before you started all go routines. Switching the order avoids this as
`read` waits until the input produced data or stopped.
=> stream: switch order of go routines started in coffin to avoid premature termination;

pkg/mdlsub/subscriber_callback.go, pkg/mon/metric_writer_cw.go
The application field for the subscriber callback was missing and therefore we tried to log a metric with a field without any value.     Removed the field from the metric as it was redundant and improved     the error message for missing values for dimensions;
=> mdlsub, mon: remove redundat application field and improved error messages for invalid dimension values;

examples/apiserver/simple-handlers/main.go, pkg/apiserver/definition.go, pkg/apiserver/server.go, pkg/test/suite_apiserver.go
With the recent refactor of the modules, it's possible to expose errors within handlers created for the apiserver.
This PR provides support to properly handle those errors within the apiserver aswell.
=> apiserver: add ctx and error to Definer;

pkg/ddb/repository_transaction.go, pkg/ddb/repository_transaction_test.go
Backoff should be configurable via the config package
=> ddb: use backoff settings for transactions;

pkg/test/docker.go, pkg/test/env/container_runner.go, pkg/test/mocks.go, pkg/test/test.go
This change should inject the correct credentials from the DOCKER_HUB_PASSWORD/USERNAME env variables if set.
=> test: use docker hub credentials from environment if possible;

pkg/cli/cli.go
If you want to run a cli module which is using the status manager you
have to add a module to the kernel. This commit allows you to run a cli
app with more than a single module so both modules can be specified. It
also allows you to apply options directly to a module factory instead of
a module to allow you to still specify module options when adding a
multi module factory.
=> cli: added option to run a cli app with more than a single module and allow applying options to a module factory;

go.sum, pkg/cloud/aws_clients.go, pkg/ddb/builder_batchgetitems.go, pkg/ddb/builder_factory.go, pkg/ddb/builder_getitem.go, pkg/ddb/builder_query.go, pkg/ddb/builder_scan.go, pkg/ddb/expr_filter.go, pkg/ddb/mocks/BatchGetItemsBuilder.go, pkg/ddb/mocks/GetItemBuilder.go, pkg/ddb/repository.go, pkg/test/suite/run.go, test/cloud/aws/dynamodb/client_test.go, test/ddb/config.dist.yml, test/ddb/ddb_test.go
DynamoDB features a TTL field on items, but still returns expired items
from the database if you query for them before they are deleted (the
deletion will happen up to two days after an item expires). Thus we
already had logic in gosoline to filter items from a Query or Scan which
have expired but are still returned by DDB. This commit extends this
behavior such that we also filter items from GetItem or BatchGetItems if
they did expire.
This commit also updates the ddb integration test to use the new test
framework and actually adds some tests.
=> ddb: change GetItem and BatchGetItem to not return expired items;

pkg/stream/output_channel.go, pkg/stream/output_channel_test.go, pkg/stream/producer_daemon.go, pkg/stream/producer_daemon_test.go
When we get writes after the producer daemon already started shutting
down, we might try to write to a closed channel. Therefore we now check
whether the channel has already been closed and, if so, drop the write
and log a warning, avoiding the panic we would otherwise get.
=> stream: avoid panic on closed channel in producer daemon;

pkg/stream/input_in_memory.go, pkg/stream/output_in_memory.go, pkg/stream/producer_daemon.go, pkg/test/suite/run.go
If you write a test case to publish a message somewhere and then confirm
it was correctly published, everything was fine. If you now add a second
such test case, suddenly the output contains a second message and you
might get the wrong message in the Assert function of your test case.
This commit fixes this by resetting inMemory outputs between tests so
they no longer share this state.
The same story basically holds true for producer daemons.
=> stream, test: Allow multiple tests to use a single inMemory output or producer daemon;

pkg/stream/consumer_base.go, pkg/stream/consumer_batch_test.go, pkg/stream/consumer_test.go, pkg/stream/producer_daemon_aggregator.go, pkg/stream/producer_daemon_aggregator_test.go
This commit is mainly a bugfix for an annoying issue we had with some integration tests. Under load the inMemory input would sometimes report it was sending messages on a closed channel. Why? Because the input was reset for the next test before the last go routine of the test returned, thus affecting the state of the next test. We now combat this by having the consumer no longer spawn a lone go routine, but instead add it to a coffin and then closing the input from there, ensuring we wait for that go routine before finishing the test and resetting the inputs.
=> stream: reduce runtime of a test and ensure we stop an input before the app terminates;

pkg/db-repo/repository.go, pkg/db-repo/repository_test.go, test/db_repo_change_history_test.go, test/db_repo_query_test.go, test/test_configs/config.db_repo_query.test.yml, test/test_fixtures/migrations_db_repo_query/1_create_tables.up.sql
This adds a verification in db_repo.Query and triggers an error if the model being queried is different than the repo metadat.
=> db_repo: add query crossing model verification and error;

pkg/apiserver/middleware_logger.go, test/apiserver/config.dist.compressed.yml, test/apiserver/config.dist.eofBind.yml, test/apiserver/eof_bind_test.go
If a client sends a request, but then loses the connection, we would log `bind error - EOF` without really making clear what happened. How we instead log `network error - client has gone away - EOF`, which is hopefully easier to understand.
=> apiserver: improve bind error message if the client lost the connection;

pkg/http/client.go, pkg/http/client_test.go, pkg/test/env/components_container.go, pkg/test/suite/testcase_apiserver.go
http: implemented `follow_redirects` config setting and moved rest of client to `http_client` config;
This commit deprecates the `http_client_retry_count` and
`http_client_request_timeout` config settings (replacing them with
warnings for now) and instead moves them to the `http_client` object
with default values of 30 seconds and 5 retries. It also implements the
`follow_redirects` config setting in the `http_client` object, allowing
you to turn off following redirects if needed (it defaults to follow
redirects).
http: implemented `follow_redirects` config setting and moved rest of client to `http_client` config;
This commit deprecates the `http_client_retry_count` and
`http_client_request_timeout` config settings (replacing them with
warnings for now) and instead moves them to the …
=> Add expected number of redirects to api test cases & implement follow_redirects for http client

pkg/log/handler_sentry.go, pkg/log/options.go
The sentry handler is writing the event id to the logger fields so subsequent log messages carry that event id. However, it was doing that in an unsafe way as it simply modified the map. This is however not allowed as the map could be read by another thread at the same time, for example if that thread is currently executing `WithFields`. Instead, we now build a completely new map with the sentry event id included. This way we can't be writing to a map which is also read at the same time and should be fine.
@j4k4 Am I correct that the intention of the code is to set the sentry_event_id field before the log message gets written to stdout (or where ever it should end up in the end)? Was a little bit confused about a handler modifying the state of the logger like that, but at least now it …
=> log: Do not write to map fields from handler as they should be read only;

pkg/cloud/aws/awsv2.go, pkg/cloud/aws/awsv2_rate_limiter.go
The AWSv2 SDK by default uses a rate limiter with capacity for 100
retries before it stops retrying. A retry needs to be paid for by 5
successful requests (so your backoff needs to be long enough and your
general traffic good enough). So if you are suddenly hitting onto a
ddb table with very limited capacity, almost all requests fail and you
exhaust the pool of retries. So requests will fail even with an infinite
retry policy. To fix this, we disable the rate limiter and only use our
backoff delayer to limit the number of requests we send to AWS.
=> cloud/aws: replace aws default rate limiter with custom rate limiter;

pkg/cloud/aws/kinesis/reader.go, pkg/stream/input_in_memory.go, pkg/stream/input_in_memory_test.go
How do you trigger a `fatal error: sync: unlock of unlocked mutex`? Just overwrite the mutex with a fresh one while it is locked! That is what the `InMemoryInput` was doing after all in its `Reset` call, so if something was still calling `Stop` on it and `Reset` was called at the same time, the mutex from the `sync.Once` would've been overwritten with a fresh, unlocked mutex. Thus we now changed the logic to make `Reset` thread-safe and also replaced another usage of `sync.Once` with a pointer to it (overwriting a pointer causes the thread using the old instance to unlock the old instance without being affected by the new
instance and thus avoids the problem).
=> stream, cloud: fixed some (potential) problems with overwriting a `sync.Once`;

pkg/mdlsub/mocks/Publisher.go, pkg/mdlsub/publisher.go
Currently the `mdlsub` publisher implementation does not allow for batching messages, while it uses the `stream.Producer` which has this capability. This PR should add this functionality.
=> mdlsub: add publisher batchwrite capability

pkg/apiserver/server.go
We need this fix to override the api port with an env variable in a dockerfile
=> config: check api_port only in config file

pkg/log/logger.go
If you take some arbitrary message and use it as a format string, you destroy the parts which randomly contain percent signs (url encoded data for example). Thus, we need to supply a format string (just %s) on our own to avoid this problem and get the message as we pass it in.
=> log: don't use the error message we constructed as a format string;

Makefile, docs/getting_started/kernel.md, pkg/application/app_test.go, pkg/application/options.go, pkg/cli/cli.go, pkg/kernel/kernel.go, pkg/kernel/kernel_options.go, pkg/kernel/kernel_test.go, pkg/kernel/middleware_test.go, pkg/kernel/stage.go, pkg/log/status/module_test.go, pkg/test/application.go, pkg/test/suite/testcase_application.go, test/guard/guard_test.go, test/stream/producer_daemon_test.go
Before this release, the kernel run function was just returning to the golang main function, which resulted in an exit code of 0 in normal cases. An exception was the forced stop which exited with code 1.
With this release, the kernel always exits with an appropriate exit code:  
- Code 0 on successful runs  
- Code 1 on errors during module boot or run
- Code 10 if there are no modules to run
- Code 11 if there are no foreground modules
- Code 12 if the kernel is forced to stop due to the kill timeout
=> kernel: return an appropriate exit code on leaving the kernel;

pkg/db-repo/notification_sns.go, pkg/mdlsub/config_postprocessor_publisher.go, pkg/stream/output_configurable.go, pkg/stream/producer.go
The publisher is able to handle the kinesis output now.
You can configure a kinesis publisher like this:  
```yaml
mdlsub:
publishers:    
todoItem: { output_type: kinesis, application: my-todo-app }
```
which will result in the following producer and output configuration:
```json
{
"stream": {
"producer": {
"publisher-todoItem": {
"compression": "none",
"daemon": {
"aggregation_max_size": 950000,
"aggregation_size": 1,
"batch_max_size": 4500000,
"batch_size": 500,
"buffer_size": 10,
"enabled": true,
"interval": 1000000000,
"message_attributes": {
"modelId": "project.family.my-todo-app.todoItem"
},
"runner_count": 10
},
"encoding": "",
"output": "publisher-todoItem"
}
},
"output": {
"publisher-todoItem": {
"stream_name": "project-env-family-my-todo-app-todoItem",
"type": "kinesis"
}
}
}
} …
```
=> mdlsub: added kinesis handler for publisher

pkg/cloud/aws/kinesis/kinsumer.go, pkg/cloud/aws/kinesis/kinsumer_test.go, pkg/cloud/aws/kinesis/metadata_repository.go, pkg/cloud/aws/kinesis/metadata_repository_test.go, pkg/cloud/aws/kinesis/mocks/MetadataRepository.go
If you change the number of shards in kinesis, you either split or combine shards. Thus, for a limited amount of time, you might have a different number of shards than you expect (e.g., when changing from 4 to 8 shards, there are 12 shards for some time, the old 4 shards and the new 8 shards). We will now ignore the 4 shards you already finished (if you are not behind on the stream) or any of the 8 new shards which have still unfinished parent shards in the set of the old 4 shards when assigning shards to clients. This also ensures you don't read data from a child shard before completing the parent shard (which would violate processing data with the same partition key in-order).
=> cloud/aws/kinesis: do not consider finished shards or shards with an unfinished parent shard for reading;

pkg/blob/store.go
This aims to solve a problem I encountered when using the BlobStoreFixtureWriter. It works along the lines of:
the `BlobFixtureWriter` calles `filepath.Abs` on the given filepath. This always returns something like `/path/to/file` which is written into `basePath`. The writer then builds the object key of the S3 fixture using `strings.Replace(file, s.basePath, "", 1)`, which returns a key that looks like `/file`. When it is then tried to build the final S3 path this code is used: `fmt.Sprintf("%s/%s", mdl.EmptyStringIfNil(prefix), mdl.EmptyStringIfNil(key))`, which returns a invalid S3 path the likes of `s3prefix//file`.
=> fixed blob store double slash bug

go.mod, go.sum, pkg/apiserver/handler.go, pkg/apiserver/server.go, pkg/apiserver/test_helper.go
Accessing request.URL.Host is empty on dev machines (e.g. when using localhost:8088 to run your server).
=> apiserver: extend request URL by dev location;

pkg/cloud/aws/kinesis/metadata_repository.go, pkg/cloud/aws/kinesis/metadata_repository_test.go
When we create the namespace for the kinsumer state, we used the application name of the stream instead of the consuming application. This caused different consumers of the same stream to share a state and only consume a portion of the events (if at all). Instead, we are now using the application id of the consumer, ensuring the states are kept separate.
=> cloud/aws/kinesis: use the application id from the app itself, not the stream we are reading

pkg/cloud/aws/dynamodb/error.go, pkg/cloud/aws/dynamodb/error_test.go
The current implementation of the ddb transaction repository can be given an item builder which specifies the `ReturnAllOld` builder option, which should lead to the repo returning the old value if an operation fails (i.e. if some condition check failed for a PutItem). The current implementation swallows this old value while converting the returned error to the hashicorp.Multierror.
=> ddb: fix transaction repo not returning old value if return all old is specified 

pkg/cloud/aws/awsv2_middleware_retry.go, pkg/cloud/aws/kinesis/kinsumer.go, pkg/cloud/aws/kinesis/kinsumer_test.go, pkg/cloud/aws/kinesis/shard_reader.go, pkg/cloud/aws/kinesis/shard_reader_test.go, pkg/conc/ddb_lock.go, pkg/conc/ddb_lock_provider_test.go, pkg/exec/context.go, pkg/exec/context_test.go, pkg/exec/executor_backoff.go, test/cloud/aws/dynamodb/client_test.go, test/fixtures/dynamodb/dynamodb_test.go, test/fixtures/mysql/mysql_test.go, test/fixtures/redis/redis_test.go
exec: added WithStoppableDeadlineContext;
When we request a file from S3, we do the initial request with a deadline and, if successful, cancel the deadline. However, this then cancels the context we need to download the body of that response - causing spurious canceled errors when downloading larger files (smaller files sometimes manage to slip through the window until the cancel is detected). To fix this, we introduce a new context type which is stopped but not canceled, so we can free the associated resources without causing this problem.
=> cloud/aws: fix context.Canceled error for larger S3 downloads;

pkg/test/suite/options_suite.go, pkg/test/suite/run.go, test/cloud/aws/dynamodb/client_test.go, test/suite/suite_test.go
- `WithTestCaseWhitelist` allows you to specify which tests to run from a larger set, so you can easily add `WithTestCaseWhitelist("TestYourMethod")` to debug the `TestYourMethod` test.
- `WithTestCaseRepeatCount` allows you to repeat a whole test suite without wrapping the `suite.Run` call in a for loop or similar. If a problem you are debugging doesn't happen every time this option helps you debug this problem.
=> test/suite: added two options to make debugging tests easier;

pkg/stream/consumer.go, pkg/stream/consumer_base.go, pkg/stream/consumer_batch.go, pkg/stream/consumer_test.go, pkg/stream/producer_daemon.go, pkg/stream/producer_daemon_test.go
- the consumer now retries messages on panic with a custom retry handler
- the producer will produce an error now if one tries to write a message with a not running daemon
=> stream: smaller bugfixes and improvements

pkg/stream/producer_daemon.go, test/stream/producer_daemon/module.go
```
=== CONT  TestProducerDaemonTestSuite
components.go:92: 
Error Trace:	components.go:92
component_stream_output.go:54
suite_test.go:30
Error:      	message not available
Test:       	TestProducerDaemonTestSuite
Messages:   	there is no message with index 0
--- FAIL: TestProducerDaemonTestSuite (8.91s)
```
=> investigate producer daemon test

pkg/apiserver/handler.go
Currently the stream handler only supports sending a POST request with a request body. If you want to use a streaming response to continually write a file (i.e. image, zip ...) continually to the HTTP client (so basically just a file download), usually issuing a GET request on URL which completely identifies the resource to download should suffice. Also when using the `download` attribute on an HTML anchor the browser is only able to issue GET requests. This PR adds a new type of stream handler, namely the `DownloadHandler` which can be used to receive GET requests and write out responses like files to the output writer.
=> apiserver: added download handler

pkg/test/env/factory_wiremock.go
We want to be able to use [response templating](https://wiremock.org/docs/response-templating/) in our integration test
=> test: add response templating to wiremock;

pkg/apiserver/crud/handler.go, pkg/apiserver/crud/update.go, pkg/application/options.go, pkg/dispatcher/dispatcher.go, pkg/share/create.go, pkg/share/handler.go, pkg/share/manager.go, pkg/share/options.go, pkg/share/policy_builder.go, pkg/share/repository.go, pkg/share/shareable_repository.go, pkg/test/suite/options_suite.go
In the future  we want to have the capability to share certain entities with users that do not have full read/write access to parts of the used software. With "sharing" we mean having users with restricted access to specific entities, enforced by guard policies. This PR adds the `share` package which provides a `crud`-like HTTP handler as well as a kernel option and a wrapper for a `db_repo.Repository`. It also defines a `Share` entity, which consists of:
* The ID of the targeted entity
* The ID of the owning entity (i.e. the user)
* The ID of the guard policy (given the SqlWarden is used)
When using this new package to create entity shares there one wants to do the following things:
1. Add the new kernel option the the target applications options - this will create a table for the new …
=> Entity sharing package

pkg/apiserver/auth/unchecked_key.go, pkg/apiserver/auth/unchecked_key_test.go
This is a breaking change. You can migrate your code without changing behavior like this:
- `auth.NewUncheckedKeyHandler(config, logger)` -> `auth.NewUncheckedKeyHandler(config, logger, auth.ProvideValueFromHeader(auth.HeaderApiKey))`
- `auth.NewUncheckedKeyAuthenticator(config, logger)` -> `auth.NewUncheckedKeyAuthenticator(config, logger, auth.ProvideValueFromHeader(auth.HeaderApiKey))`
=> apiserver/auth: added new mandatory parameter to specify the apiKey provider to NewUncheckedKeyHandler and NewUncheckedKeyAuthenticator

pkg/mdlsub/delay_op.go, pkg/mdlsub/delay_op_test.go, pkg/mdlsub/subscriber_callback.go
If your subscriber needs to wait before persisting a model, it can now return mdlsub.NewDelayOpError(err) from the transformer. This will then cause only a note get logged instead of an error and the model eventually retried.
=> mdlsub: allow delaying persisting subscribed models

pkg/apiserver/middleware_metric.go
- / would be trimmed to an empty string should you have a route there, now we write the metric with / as path
- unknown routes also return an empty string, we don't need to write metrics for them
=> apiserver: don't trigger an error for unknown routes or /;

pkg/cloud/aws/awsv2.go, pkg/cloud/aws/sqs/naming.go, pkg/cloud/aws/sqs/naming_test.go, pkg/cloud/aws/sqs/service.go, pkg/stream/input_configurable.go, pkg/stream/input_sns.go, pkg/stream/input_sqs.go, pkg/stream/mpr_queue_names.go, pkg/stream/output_configurable.go, pkg/stream/output_sqs.go, pkg/stream/retry_sqs.go
To make it easier to configure different naming pattern for different sqs clients, we want to be able to configure the queue name patterns on client level:
```
cloud:
aws:
sqs:
clients:
account_a:
naming:
pattern: {env}-{family}-{app}-{queueId}
account_b:
naming:
pattern: {app}_{queueId}
```
=> sqs: use a configurable naming pattern instead of a coded strategy

pkg/redis/client.go, pkg/redis/client_test.go, pkg/redis/mocks/Client.go, test/apiserver/compressed_test.go
removed `withScores` parameter from `ZRandMember` as it doesn't do anything (go-redis bug, fixed in later version and then removed from signature)
added support for optional arguments in `ZADD` and `ZRANGE`
- `ZAddArgs`
- `ZAddArgsIncr`
- `ZRangeArgs`
- `ZRangeArgsWithScore`
added following redis operations, which all are supported since redis 1.0.0
- `LPush`
- `LRem`
- `RPop`
- `SDiff`
- `SDiffStore`
- `SInter`
- `SInterStore`
- `SMembers`
- `SMove`
- `SPop`
- `SRem`
- `SRandMember`
- `SUnion`
- `SUnionStore`
=> redis: added LPush, LRem, RPop and all redis 1.0.0 set operations

pkg/funk/slice.go, pkg/funk/slice_test.go, pkg/test/suite/testcase_application.go
With the current implementation of the application test suite we can run into problems with foreground modules:
If we have some module running in the service stage that coordinates its exit using the context provided by the kernel that our test depends on, the test will be started in the application stage. If the test application then exists, the kernel package will not teardown modules in the service or essential stage, which will lead to our service being run indefinitely.
This PR makes every module in the application stage (the app under test) an essential module, which will lead to all other modules being teared down correctly.
=> Fix blob runner test suite exit

.github/workflows/go.yml, go.mod, go.sum, pkg/http/client.go
We want to update the resty version, as our PR was merged to support resetting io.ReadSeekers for files when they were read by the client. This lead to problems in services before as the reader is exhausted and the data can no longer be accessed in case of a retry.
=> http: added retry reset readers to http client configuration;

pkg/apiserver/definition.go, pkg/apiserver/middleware_metric.go
before publishing data points to metrics, in or log we get this error:
```
invalid metric dimension: 1 error occurred:
* invalid dimension 'path' = '' for metric NAME, this will later be rejected
```
The issue is that we send '/' as the path, but due to the use of TrimRight in the getAbsolutePath() method, the path gets deleted. To resolve this problem, we can add an 'if' statement to check whether the absolutePath is empty, and if so, we can add '/' to it.
=> fixing the issue for invalid dimension

pkg/db-repo/change_history_manager.go, pkg/funk/slice.go, pkg/funk/slice_test.go
This fixes a bug when migration change history tables caused by having models specified more than once and running migrations in parallel.
=> Fix change history migration

pkg/cloud/aws/kinesis/kinesis.go, pkg/cloud/aws/kinesis/kinsumer.go, pkg/cloud/aws/kinesis/record_writer.go, pkg/cloud/aws/sqs/queue.go, pkg/ddb/repository.go, pkg/stream/consumer_base.go, pkg/stream/producer.go
This is a first (untested) draft for adding the client name to all inputs/outputs that are metadata aware
=> added aws_client_name to all metadata aware inputs and outputs

pkg/ddb/service.go, pkg/ddb/service_test.go, pkg/ddb/settings.go
if there are no capacity values configured, we should go with a value of 1
=> ddb: sanitize settings with more default values

pkg/cfg/config.go, pkg/cfg/config_test.go, pkg/cfg/environment.go, pkg/cfg/environment_test.go, pkg/cfg/mocks/Config.go, pkg/cfg/mocks/GosoConf.go, pkg/cloud/aws/credentials.go, pkg/cloud/aws/credentials_test.go
checks if there are config keys with a prefix
=> cfg: added check for key prefixes;

pkg/apiserver/handler.go
Fixes a panic, that occurs when the `/` route is hit, for example when registered like this:
```go
package main
import (
"context"
"fmt"
"github.com/gin-gonic/gin"
"github.com/bogdanfinn/tls-client-api/internal/tls-client-api/api"
"github.com/justtrackio/gosoline/pkg/cfg"
"github.com/justtrackio/gosoline/pkg/log"
)
func main() {
r := gin.Default()
config := cfg.New()
logger := log.NewLogger()
forwardedRequestHandler, err := api.NewForwardedRequestHandler(context.Background(), config, logger)
if err != nil {
panic(fmt.Errorf("can not create forwardedRequestHandler: %w", err))
}
// from my limited debugging, registering it as "/" here causes the ginUrl obtained with ginUrl := location.Get(ctx)
// to be nil, which then makes the mergo.Merge call panic
r.POST("/", forwardedRequestHandler) …
```
=> apiserver: Fix panic for Gin handlers registered on the main ("/") route

pkg/conc/ddb/leader_election_ddb.go
This release adds the possibility to configure the ddb client which should be used for the ddb leader election implementation.  
E.g. if you want to change the ddb client for the leader election in the `MessagesPerRunnerMetricWriter`, you can do so via:
```yaml
conc:
leader_election:
streamMprMetrics:
client_name: you-custom-client-name
```
=> conc: adds the option to configure the client name for ddb leader election

go.mod, go.sum, pkg/guard/audit_logger.go, pkg/guard/guard.go, pkg/guard/guard_test.go, pkg/guard/manager_sql.go, pkg/guard/mocks/AuditLogger.go, pkg/guard/mocks/Guard.go, pkg/guard/mocks/Manager.go, pkg/share/create.go, pkg/share/handler.go, pkg/share/policy_builder.go, pkg/share/repository.go, pkg/share/shareable_repository.go, test/guard/guard_test.go
If you want to provide additional contextual information, you need to pass on the context to the logger in your guard audit. Hence we switched to a fork which supports `context.Context` as a parameter.
Additionally you can now configure the audit logger and enable / disable both grant and rejection logs. By default, grants are disabled / rejections are enabled. You can adjust this like the following:
```yaml
guard:
audit:
log_grants: false
log_rejections: true
```
=> guard: make it context aware and the audit logs configurable

docs/README.md, docs/docs/components.jsx, docs/docs/overview.mdx, docs/docs/quickstart/api-server/create-an-api-server.mdx, docs/docs/quickstart/api-server/src/create-an-api-server/handler.go, docs/docs/quickstart/api-server/src/create-an-api-server/main.go
This adds a new MDX `CodeBlock` component that supports snippets.
Example usage (more detailed instructions included in the README):
```yaml
port: 80
host: example.com
struct_example:
port: 80
host: example.com
timeout: 5s
threshold: 100
```
```go
package main
import (
"github.com/justtrackio/gosoline/pkg/cfg"
)
// snippet-start: main
func main() {
config := cfg.New()
// snippet-start: configure options
options := []cfg.Option{
cfg.WithConfigSetting("host", "localhost"),
cfg.WithConfigSetting("port", "80"),
}
// snippet-end: configure options
if err := config.Option(options...); err != nil {
panic(err)
}
}
// snippet-end: main
```
```mdx
import { CodeBlock } from '../components.jsx';
<CodeBlock showLineNumbers language="yaml" snippet="example">{ConfigDist}</CodeBlock>
<CodeBlock …
```
=> Add custom CodeBlock component

pkg/guard/manager_sql.go, test/guard/fixtures_test.go, test/guard/guard_test.go, test/guard/migrations/01_add_guard_policy.up.sql
Increases guard table transparency by unifying guard tables. The original library uses JSON policies, the changes allows us to switch to JSON representation of the policy instead of the fully-denormalized way
=> guard: unify guard tables;

pkg/cloud/aws/awsv2_delayer.go, pkg/cloud/aws/awsv2_delayer_test.go, pkg/mapx/struct.go
The backoff delayer uses a random source which is not thread safe. As it is itself used by multiple threads at the same time, it needs to be thread safe, therefore we need a lock around the access to the random source.
=> cloud: fix a race in the backoff delayer;

pkg/apiserver/health_check.go, pkg/apiserver/middleware_logger.go, pkg/apiserver/server.go
Enables to log the request body for incoming http requests via configuration:
```yaml
api:
port: 8080
logging:
request_body: true
request_body_base64: true
``` 
If needed the body can be encoded in base64 if `request_body_base64` is set to true.
=> apiserver: enable request body logging via settings

pkg/http/client.go
Adds a configuration flag `disable_cookies` to the http client.
after this change you should be able to configure a http client without cookies. It shouldn't have any breaking changes, the default option is with cookies enabled.
usage example:
```
http_client:
default:
request_timeout: 1s
retry_count: 3
follow_redirects: false
disable_cookies: true
```
=> http: add disable_cookies config flag;

pkg/lambda/error.go, pkg/lambda/lambda.go
This change enables the option to set up the handlers of the logger via configuration.
=> lambda: changed logger initialization to get handlers from config

docs/docs/how-to/logging/src/complex-logger/main.go, docs/docs/quickstart/api-server/create-a-money-exchange-app.mdx, docs/docs/quickstart/api-server/src/create-a-money-exchange-app/handler.go, docs/docs/quickstart/testing/src/integration-test-api/handler.go, docs/docs/reference/package-log.mdx, docs/docs/reference/src/log/usage.go, examples/apiserver/simple-handlers/handlers.go, pkg/apiserver/handler.go, pkg/apiserver/middleware_logger.go, pkg/apiserver/mocks/HandlerWithInput.go, pkg/apiserver/mocks/HandlerWithMultipleBindings.go, pkg/apiserver/mocks/HandlerWithStream.go, pkg/apiserver/mocks/HandlerWithoutInput.go, pkg/application/app.go, pkg/application/error.go, pkg/application/options.go, pkg/cloud/aws/kinesis/record_writer.go, pkg/cloud/aws/kinesis/record_writer_test.go, pkg/lambda/lambda.go, pkg/log/context.go, pkg/log/context_test.go, pkg/log/logger.go, pkg/log/logger_message_encode_handler.go, pkg/log/logger_message_encode_handler_test.go, pkg/log/options.go, pkg/stream/consumer.go, pkg/stream/consumer_base.go, pkg/stream/consumer_test.go
This commit introduces a distinction between local and global logger fields in a context (there used to be only global fields in the past). Global fields are forwarded to downstream services when using the stream framework while local fields are kept local to the current application. This can be useful to establish fields shared for the duration of a single request between different services without affecting downstream services.
Additionally, this commit introduces the notation of mutating these fields. If a context already contains fields, a callee can thus change fields in a context, allowing the caller to also log these fields. Support was added for the stream and apiserver frameworks already - when handling a message or a request, we are now able to log the returned error in case of …
=> log: Split logger fields into local and global fields and made them mutable

pkg/cloud/aws/kinesis/kinesis.go, pkg/ddb/metadata_factory.go, pkg/ddb/naming.go, pkg/ddb/settings.go, pkg/tracing/aws.go, pkg/tracing/tracer_aws.go
When creating a ddb table for an integration test, we would ensure there was at least 1 capacity set for read and write capacity. We also tried the same for GSIs, but we only updated a local variable and not the actual setting. This PR fixes the issue.
Additionally, we now report the name of a kinesis stream we failed to find, making debugging easier.
=> ddb: use 1 capacity if no capacity setting was provided

pkg/httpserver/auth/jwt_auth.go, pkg/httpserver/auth/jwt_token_handler.go
This release fixes an issue with configuring JWT auth handlers on http servers.  
The signature updates from:
```golang
func NewJWTAuthAuthenticator(config cfg.Config) Authenticator
```
to
```golang
func NewJWTAuthAuthenticator(config cfg.Config, name string) Authenticator
```
The name corresponds to the httpserver in the config. With this one can configure different JWT auth handlers for each http server.
```yaml
httpserver:
default:
auth:
jwt:
signingSecret: 4812bd82-2e5b-4c8a-8559-eee08b03fea9
issuer: justtrack
```
=> httpserver: fixes httpserver jwt auth

pkg/cfg/config_strings_test.go, pkg/cfg/testdata/config.strings.test.yml, pkg/test/suite/testcase_httpserver.go
Fixes an issue with httpserver based integration tests in which the http port wasn't randomized.
=> httpserver: fixes integration testsuite

docs/docs/quickstart/http-server/src/create-a-money-exchange-app/handler.go, docs/docs/reference/package-test.mdx, pkg/stream/retry_noop.go, pkg/stream/testdata/encoding_test.pb.go, pkg/stream/testdata/message_builder_test.pb.go, pkg/test/env/components.go, pkg/test/env/components_config_manager.go, pkg/test/env/config.default.yml, pkg/test/env/container_runner.go, pkg/test/env/environment.go, pkg/test/env/factory_ddb.go, pkg/test/env/factory_localstack.go, pkg/test/env/factory_mysql.go, pkg/test/env/factory_redis.go, pkg/test/env/factory_s3.go, pkg/test/env/factory_wiremock.go, test/cloud/aws/dynamodb/client_test.go, test/stream/retry_handler_sqs/testdata/data_model.pb.go
Test components are docker container like wiremock or localstack which support you in your integration tests to mock
your applications infrastructure.
The used image for a component can be configured on a global and on a per component level. The following configuration
snipped shows a config for two wiremock components. **mockA** gets the image configuration from the global level which is
configured via the key `test.defaults.images.wiremock` and **mockB** has local configuration. With this, **mockA** gets
tag `3.4.0` and **mockB** gets `3.3.0`.
```yaml
test:
defaults:
images:
wiremock:
repository: wiremock/wiremock
tag: 3.4.0
components:
wiremock:
mockA:
expire_after: 5m
mockB:
image:
repository: wiremock/wiremock
tag: 3.3.0
expire_after: 5m
```
=> test: component repository and image tags are configurable now

docs/docs/reference/package-cloud_aws.mdx, pkg/cloud/aws/awsv2.go, pkg/cloud/aws/credentials.go, pkg/cloud/aws/kinesis/naming.go, pkg/ipread/provider.go, pkg/ipread/provider_maxmind.go, pkg/ipread/provider_memory.go, pkg/ipread/reader.go, pkg/ipread/refresh_module.go, pkg/ipread/settings.go, pkg/kernel/stage.go, pkg/test/env/container_runner.go
This release enables pulling geoip database files from s3 and automatic refresh of those.  
To load the database file from s3 and refresh it every hour, set up the following config:  
```yaml
ipread:
default:
provider: maxmind
database: s3://my-bucket-with-geoip-databases/geoip_latest.tar.gz
refresh:
enabled: true
interval: 1h
```
Refreshing the database is happing in a background kernel module, so you have to add following kernel module factory:
```golang
func main() {
application.RunHttpDefaultServer(
api.DefineRouter,
application.WithModuleMultiFactory(ipread.RefreshModuleFactory),
)
}
```
=> ipread: added kernel module to pull database updates from s3

pkg/cloud/aws/kinesis/metadata_repository.go, pkg/cloud/aws/kinesis/metadata_repository_test.go, pkg/http/client.go, pkg/mdlsub/publisher.go
This adds a whole bunch of settings relating to the http transport. You can configure them like this:
```yml
http_client:
default:
transport:
tls_handshake_timeout: 10s
disable_keep_alives: false
disable_compression: false
max_idle_conns: 100
max_idle_conns_per_host: 0
max_conns_per_host: 0
idle_conn_timeout: 90s
response_header_timeout: 0s
expect_continue_timeout: 1s
max_response_header_bytes: 0
write_buffer_size: 0
read_buffer_size: 0
dialer:
keep_alive: 30s
timeout: 30s
dual_stack: true
fallback_delay: 0s
```
=> http: allow configuring the HTTP transport for a client

pkg/cloud/aws/credentials.go, pkg/cloud/aws/credentials_default.go, pkg/cloud/aws/credentials_default_test.go, pkg/cloud/aws/credentials_integrationtest.go, pkg/cloud/aws/credentials_integrationtest_test.go, pkg/cloud/aws/credentials_test.go
When running tests with localstack you previously needed to have set the AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID env vars. This collides with eg aws-sso-cli which is refusing to operate when these are set.
Without setting them the autocreate functionality of gosoline against localstack would not work.
This PR uses the previously unused const values with default authentication credentials as a fallback option when no other means of authentication are set / provided.
By default these consts are empty. When compiling with the integration tag they get set to a non empty default value which is sufficient for localstack to work with autocreation.
=> cloud/aws: Use the default credential constants as the last option for aws credential provider

pkg/httpserver/handler_test.go, pkg/kernel/kernel.go, pkg/kernel/kernel_test.go, pkg/kernel/stage.go
There used to be a rare race condition in the kernel when a module
failed and returned an error. The kernel would then proceed to shut
down, but this could be started before the module was actually done and
had returned that error to the coffin it was running in. The coffin
would then receive the error for the kernel shutting down and ignore the
(slightly later received) error from the module. This would cause the
kernel to issue a success return code instead of signaling failure to
its parent process.
We now kill the coffin of the stage with the failed module with the
error returned from the module of the stage. Even if the race now
triggers, we still return the correct error. Should two modules from
different stages fail at the same time there is a small chance that one
stage still …
=> Fix kernel race

pkg/conc/task_runner/task_runner.go
When having the task runner enabled, it adds a foreground module to the app. So every application, which adds additional ones, will have troubles shutting down for themselves, as there is always a second foreground module for which the kernel is waiting.
This change disables the task runner by default, so you have to be aware about the implications.
=> conc: disabled task runner by default;

pkg/cloud/aws/kinesis/checkpoint.go, pkg/cloud/aws/kinesis/kinsumer.go, pkg/cloud/aws/kinesis/metadata_repository.go, pkg/cloud/aws/kinesis/metadata_repository_test.go, pkg/cloud/aws/kinesis/mocks/Checkpoint.go, pkg/cloud/aws/kinesis/mocks/CheckpointWithoutRelease.go, pkg/cloud/aws/kinesis/shard_reader.go, pkg/cloud/aws/kinesis/shard_reader_test.go
When a Kinesis stream doesn't get any messages for a day (on default message expiration of one day), the last sequence number we have stored becomes invalid and we effectively start consuming the stream from the start each time our consumer restarts. To prevent this, we now also store the last shard iterator in case we didn't receive any messages in the last batch. Then, we can resume consuming from the shard iterator and only fall as much behind as we took to restart the consumer.
Closes #1123
=> cloud/aws/kinesis: allow resuming consuming empty kinesis streams;

pkg/httpserver/auth/auth.go, pkg/httpserver/auth/jwt_token_handler.go, pkg/httpserver/auth/settings.go
The idea here is that we can restrict in the config.dist.yml what authentication options are available. The same can be done with env vars, or we can layer env vars over the config.dist.yml to allow again all (eg disallow one method by default and for certain environments it could be turned on again).
In code we would specify our auth handler like this:
```go
auth.NewChainHandler(auth.OnlyConfiguredAuthenticators(config, "default", map[string]auth.Authenticator{
auth.ByApiKey:    apiKeyAuthHandler,
auth.ByGoogle:    googleAuthHandler,
auth.ByBasicAuth: emailAuthHandler,
}))
```
and could restrict them to eg just Google and BasicAuth like this in the config.dist.yml:
```yaml
httpserver:
default:
auth:
allowedAuthenticators:
- google
- basicAuth
```
All APIKey auths would then result in …
=> allow restricting available auth options through config

pkg/fixtures/named.go, pkg/httpserver/auth/jwt_token_handler.go, pkg/httpserver/auth/mocks/JwtTokenHandler.go
This allows you to sign claims with custom data, for example to implement custom auth flows.
=> httpserver/auth: Added method to JwtTokenHandler to sign claims directly to make it extensible

pkg/fixtures/named.go, pkg/fixtures/writer_configurable_kvstore.go, pkg/fixtures/writer_ddb_kvstore.go, pkg/fixtures/writer_redis_kvstore.go
This release adds some small simplification for the kvstore fixtureset factories by removing a redundant type declaration.\
In addition, we added 2 little helper to create named fixtures.
=> fixtures: removed redundant type declarations for kvstore fixtures;

go.mod, pkg/fixtures/loader.go, pkg/fixtures/named.go, pkg/fixtures/purger_dynamodb.go, pkg/fixtures/simple_fixture_set.go, test/guard/fixtures_test.go
When purging a table in ddb, we delete and re-create it. However, this currently fails if the table doesn't exist yet. As deleting a non-existing table achieves our goal (of the table no longer existing), we don't need to treat this as an error.
Additionally, removing the pointer receiver from `fixtures.NamedFixtures` allows for easier usage of the type without impacting performance too much (if at all).
=> fixtures: remove pointer receiver from NamedFixtures and allow purging tables which don't exist (yet) in ddb

pkg/application/options.go, pkg/stream/consumer_base.go, pkg/stream/consumer_settings.go, pkg/test/suite/options_suite.go, pkg/test/suite/testcase_application.go
This PR includes two new options for the `github.com/justtrackio/gosoline/pkg/test/suite` package:
As the automatic config debug logs got dropped with one of the recent releases, which get printed on application start,
we added the `WithConfigDebug` option to enable it again if needed.
This new option disables all custom retry handlers for consumers. Most of the tests don't need them and they could have some potential side effects one would want to avoid during test execution.
=> test: added option to disable all custom consumer retries

pkg/fixtures/kernel_middleware.go
Currently, fixture loaders will get created, even if the fixture loading is disabled in the config.\
In certain scenarios this could cause issues.\
To improve it, this PR ensures, that the fixture loading middleware does nothing if disabled.
=> fixtures: on disabled fixtures, the middleware will do nothing now

go.mod, pkg/db-repo/change_history_manager.go, pkg/db-repo/change_history_manager_test.go, test/db-repo/change_history/entity/config.test.yml, test/db-repo/change_history/schema/config.test.yml
The goose migrations don't work well if there are untracked changes happening through the change history auto-migration feature. To be able to track the change history tables through goose, I want to be able to deactivate the automatic execution of the change history schema updates.
By default, it's deactivated. When changes are detected, it prints the corresponding schema changes but throws an error to notify the user.
=> [db-repo]: disable change history migration by default;

pkg/db/client.go, pkg/db/driver_cratedb.go, pkg/db/driver_factory.go, pkg/db/driver_mysql.go, pkg/db/driver_redshift.go, pkg/db/mocks/Client.go
This release changes the interface of the `db.Client` to use the transaction type `sqlx.Tx` instead of the native `sql.Tx` in its transaction functions:
```golang
type Client interface {
...
WithTx(ctx context.Context, ops *sql.TxOptions, do func(ctx context.Context, tx *sql.Tx) error) error
...
}
```
changed to
```golang
type Client interface {
...
WithTx(ctx context.Context, ops *sql.TxOptions, do func(ctx context.Context, tx *sqlx.Tx) error) error
...
}
```
=> db: using transactions from the sqlx package instead of native sql

pkg/ipread/refresh_module.go
The `ipread` package has a kernel module which handles automatic updates of the ip database.\
If the automatic refresh is disabled, the module exists after the initial load and marks the module as unhealthy, so that the app never gets healthy. To fix this, the health state of the module will be kept healthy on exit if refresh is disabled.
=> ipread: fixed module health issue with disabled refresh

pkg/httpserver/handler.go, pkg/httpserver/sql/query_builder.go, pkg/httpserver/sql/query_builder_test.go
We didn't check the operator and bool fields from the CRUD list query input in the past. An attacker could use them to add arbitrary conditions to their queries, creating either very slow queries or accessing data they don't actually are allowed to access.
=> httpserver/sql: fixed possible SQL injection for CRUD list routes;

pkg/httpserver/sql/query_builder.go, pkg/httpserver/sql/query_builder_test.go
This fixes the use of an empty filter. The previous commit would result in complaints about wrong booleans being used we required it to be set to "AND" or "OR".
=> httpserver/sql: allow any value for the bool field of a filter if the field is unused

pkg/kernel/kernel.go, pkg/kernel/stage.go, pkg/stream/consumer_base.go, pkg/stream/consumer_batch_test.go, pkg/stream/consumer_settings.go, pkg/stream/consumer_settings_test.go, pkg/stream/consumer_test.go, test/stream/retry_handler_sqs/config.dist.yml
If we get a context cancel while processing a message from something like kinesis, writing to the retry queue would also happen on a canceled context, failing immediately and loosing our message. We need some small delay for the cancel to prevent this.
=> stream: delay context cancels for retry messages to ensure we can write them to the retry queue

pkg/test/suite/run.go, pkg/test/suite/testcase_application.go, pkg/test/suite/testcase_application_test.go, pkg/test/suite/testcase_base.go, pkg/test/suite/testcase_base_test.go, pkg/test/suite/testcase_httpserver.go, pkg/test/suite/testcase_httpserver_extended.go, pkg/test/suite/testcase_httpserver_extended_test.go, pkg/test/suite/testcase_httpserver_test.go, pkg/test/suite/testcase_stream.go, pkg/test/suite/testcase_stream_test.go, pkg/test/suite/testcase_subscriber.go, pkg/test/suite/testcase_subscriber_test.go
If you have complex logic generating test cases, it can be helpful to be able to generate a map of test cases to run. Normally, you would then use `t.Run(name, func() {...})` to execute each test case, but this isn't an option when using the test suite to run http or stream test cases. Therefore, we now allow you to return a `map[string]T` where `T` is either a `ToHttpserverTestCaseList` interface or directly a `[]*HttpserverTestCase` slice.
Additionally, the `HttpserverTestCaseListProvider` type was added to allow you to return a function creating the test cases. The function runs after fixtures (and the app itself) have been loaded compared to the test case generator (which runs before the app has been loaded).
---
This expands the test case map logic from the http server test cases to …
=> test/suite: accept maps of tests and run them as sub-tests

examples/fixtures/sqlx/main.go, pkg/db-repo/change_history_manager.go, pkg/db/client.go, pkg/metric/daemon.go
We sometimes have code which would iterate an sql.Rows object, returning an error if we failed to read the next row. As long as we don't get an error, this works, as calling `rows.Next()` will eventually close the rows object once the last row was read. However, in case of an error we have to make sure to explicitly call `rows.Close()`, otherwise we leak connections for some drivers.
=> db: close the sql.Rows object once we are done with it

pkg/cloud/aws/athena/repository_raw.go, pkg/cloud/aws/athena/repository_test.go
If AWS responses with *Amazon Athena experienced an internal error while executing this query. Please try submitting the query again* while executing an Athena query, the client will trigger an automatic retry now.
=> cloud/aws/athena: automatic retry on internal query errors

pkg/db-repo/change_history_manager.go, pkg/db-repo/orm.go, pkg/db-repo/repository.go, pkg/mdlsub/output_db.go, pkg/share/manager.go, pkg/test/suite/testcase_subscriber.go
This release enables the use of different db client names on creating orm instances.
=> db-repo: use db client on creating orm instances

docs/docs/quickstart/http-server/create-an-http-server.mdx, docs/docs/quickstart/http-server/src/create-an-http-server/handler.go, pkg/dispatcher/dispatcher.go, pkg/dispatcher/repository_db.go, pkg/exec/error.go, pkg/httpserver/crud/errors.go, pkg/httpserver/handler.go, pkg/httpserver/handler_test.go, pkg/httpserver/middleware_logger.go, pkg/httpserver/middleware_logger_test.go
**HTTP Server**
The standard http server treats external context cancellations and disconnects as errors; even though the client may have closed or canceled the request on purpose.
As a follow up to https://github.com/justtrackio/gosoline/pull/1178 (targeting the crud handlers), this PR is adjusting the standard behaviour of any other handler similarly.
The most common use cases:
- access forbidden transformed into HTTP 403
- context cancellation / disconnects are transformed into HTTP 499
- any other error being transformed into a HTTP 500
The logger middleware is also adjusted appropriately, logging connection and request cancelations as level info. Bind errors and render errors are continously logged as warnings; by default any other error is logged as an error.
**Exec*
- fixing bugs …
=> httpserver: don't treat request cancels as errors;

docs/docs/quickstart/testing/src/integration-test-server/server_test.go, pkg/application/options.go, pkg/fixtures/kernel_middleware.go, pkg/fixtures/loader.go, pkg/fixtures/loader_noop.go, pkg/fixtures/post_processor.go, pkg/test/env/environment.go, pkg/test/suite/options_suite.go, pkg/test/suite/run.go, test/db-repo/change_history/entity/change_history_test.go, test/db/migration-golang-migrate/mysql_test.go, test/db/migration-goose/mysql_test.go, test/fixtures/dynamodb/dynamodb_test.go, test/fixtures/kvstore/configurable_kvstore_test.go, test/fixtures/mysql/mysql_test.go, test/fixtures/redis/redis_test.go, test/fixtures/s3/s3_test.go, test/guard/guard_test.go, test/mdlsub/fixtures_test.go
Major change of this release is the additions of post processors to the fixture package. These allow additional handling after loading the fixture data, e.g. populating internal caches. For this change, the signatures of adding fixtures has changed slightly:
```golang
func main() {
application.RunHttpDefaultServer(
api.DefineRouter,
application.WithFixtureSetFactory("default", service.FixtureSetsFactory, service.PostProcessor),
)
}
```
or if you want to add multiple groups with the same post processor:
```golang
func main() {
application.RunHttpDefaultServer(
api.DefineRouter,
application.WithFixtureSetFactories(map[string]fixtures.FixtureSetsFactory{
"group1": service.FixtureSetsFactory1,
"group2": service.FixtureSetsFactory2,
}, service.PostProcessor),
)
}
```
The options for creating …
=> fixtures: added post processors to loaders

pkg/mdlsub/transformer.go, pkg/mdlsub/transformer_test.go, test/mdlsub/transformers.go
This release adds a small helper for mdlsub transformers.  
Instead of implementing the `GetInput` and  `GetModel` functions, one can embed the `TypesProvider`.  
```golang
type TestTransformer struct{}
func (t TestTransformer) GetInput() any {
return &TestInput{}
}
func (t TestTransformer) GetModel() any {
return &TestModel{}
}
```
```golang
type TestTransformer struct {
mdlsub.TypesProvider[TestInput, TestModel]
}
```
=> mdlsub: types provider util for transformers

pkg/appctx/appctx.go, pkg/guard/guard.go, pkg/guard/manager_cache.go, pkg/httpserver/middleware_logger.go, pkg/reqctx/reqctx.go, pkg/reqctx/reqctx_test.go, pkg/stream/consumer.go
We can do a lot of queries for the same policies if your response contains multiple objects you have to do access control on (e.g., returning a list of entities). To help here, we introduce a cache for the current request to avoid retrieving the same policies again and again.
=> guard, reqctx: added cache to guard for current request and reqctx package to store data for the current request

.github/workflows/go.yml, .tool-versions, go.mod, pkg/mapx/map.go, pkg/mapx/map_test.go, pkg/mapx/mapnode.go, pkg/mapx/struct_decode.go, pkg/mapx/struct_test.go
Under certain circumstances you can trigger a `fatal error: concurrent map iteration and map write` within the config; especially when using multiple modules reading / writing in parallel.
This MR adds deepcopying to the basic `Get` to mitigate this issue.
=> cfg: return deepcopy on Get;

pkg/blob/runner.go, pkg/cast/string.go, pkg/cli/cli.go, pkg/cloud/aws/sqs/attributes_test.go, pkg/conc/lazy_test.go, pkg/conc/scheduler/scheduler_test.go, pkg/db-repo/change_history_manager.go, pkg/exec/error_canceled.go, pkg/exec/error_canceled_test.go, pkg/funk/slice_test.go, pkg/metric/channel.go, pkg/metric/daemon.go, pkg/metric/daemon_test.go, pkg/metric/prometheus_metric_server.go, pkg/metric/writer.go, pkg/stream/consumer_base.go, pkg/stream/input_sqs.go, pkg/stream/output_sqs_test.go, pkg/test/env/container_runner.go, pkg/test/suite/testcase_httpserver_extended.go, pkg/test/suite/testcase_stream.go, test/httpserver/compressed_test.go
The metric daemon could run into two different deadlocks:
- Writing a metric to a full queue while the daemon was shutting down: In this case, the daemon was waiting for the lock on the metric channel struct, but the metric channel struct was busy writing to the channel and waiting for the daemon to read something from it.
- Writing a metric after an invalid metric: With proper timing, one could fill up the metric channel after the metric daemon took out an invalid message. Now the metric daemon would try to write a warning, which itself would write another metric. But the channel was already full and the metric daemon was now stuck waiting for itself reading a message from it.
This is now solved by changing the metric channel to only feature a single flag (are metrics available) and …
=> metric: limit warning logs and change metric queue to unbounded queue

pkg/funk/slice.go, pkg/funk/slice_test.go, pkg/httpserver/crud/errors.go, pkg/httpserver/handler.go, pkg/httpserver/handler_test.go, pkg/validation/error.go
For custom httpserver handlers it's good to unify the error handling as well; similar as for the crud handlers.
This release handles the validation.Error error and returns a HTTP 400 with the default error handling.
Additionally, some minor improvements for funk and validation are made to use them more comfortably.
=> httpserver, funk: handle validations and provide methods to box/unbox slice elements

go.mod, pkg/cfg/config.go, pkg/cfg/debug.go, pkg/funk/map.go, pkg/funk/map_test.go, pkg/funk/set.go, pkg/funk/set_test.go, pkg/funk/slice.go, pkg/httpserver/rpr_handler.go, pkg/log/mocks/factory.go, pkg/mdl/factory.go, pkg/mdlsub/subscriber_core.go, pkg/metric/daemon.go, pkg/stream/consumer_settings.go, pkg/test/env/logging.go, pkg/tracing/otel_trace_provider.go, pkg/tracing/tracer.go
- funk.MergeMapsWith: Combine maps, but select elements using a function instead of using the one from the last map
- funk.IntersectMapsWith: Intersect maps, but use a combination function again
- funk.MapKeysWith: When mapping two keys to the same one, use a combination function to produce the final value
- funk.PopulateMap, funk.PopulateMapWith: Create a map from a list of keys and a single value or a function generating values from the keys
- mdl.IsEmpty: Simple check if something is the zero value
- mdl.FirstNonEmpty: Convenience function to select the first provided value which is not empty
=> funk, mdl: added some more convenience functions (and tests)

pkg/reslife/lifecycle_manager.go, pkg/reslife/settings.go, pkg/reslife/settings_test.go
In some cases there is more fine grained control needed about which resources should get handled by the life cycle manager and which not. To enable this advanced control, this release adds exclude lists to all life cycles.  
These can be set via config:
```yaml
resource_lifecycles:
create:
enabled: true
excludes: [db/.*]
init:
enabled: true
register:
enabled: true
purge:
enabled: false
```
The excludes setting is a list of strings which will get interpreted as regular expressions.  
If the id of a resource matches one of the patterns, it will get excluded of that specific life cycle management.  
In case of the previous example, the create life cycle will not get executed for all db resources.
=> reslife: resource exclude patterns

pkg/cloud/aws/ssm/systems_manager.go, pkg/httpserver/health_check.go, pkg/httpserver/server.go, pkg/mapx/struct.go, pkg/mapx/struct_test.go, pkg/reslife/settings_test.go, pkg/test/suite/testcase_httpserver_extended_test.go
The current httpserver gets closed once the kernel gets stopped which can result in connection issues if there are still open connections or if the app still gets new connections.  
This release enables more graceful shutdown behaviour for the httpserver by implementing 2 additional timeouts:
```yaml
httpserver:
default:
timeout:
drain: 30s
shutdown: 30s
```
On kernel stop, the httpserver module will get unhealthy but won't close the server until the configured *drain* timeout runs out. In this time frame the orchestrator can adjust the traffic flow, so that the app won't get any new connections. After draining, the http server shuts down and will wait for at most the configured *shutdown* timeout to handle all remaining open connections.
=> httpserver: graceful server shutdown

pkg/limit/middleware_metrics.go
The existing metric names for the limit package are not compatible with Prometheus - they contain dashes.
This MR exchanges them for underscores.
=> [limit]: update metric name for prometheus compatability;

docs/docs/how-to/logging/implement-a-log-handler.mdx, docs/docs/how-to/logging/src/complex-logger/main.go, docs/docs/how-to/logging/src/config-logger/config.dist.yml, docs/docs/how-to/logging/src/log-handler/main.go, docs/docs/how-to/logging/src/minimal-logger/main.go, docs/docs/reference/src/log/custom_handler.go, docs/docs/reference/src/log/main.go, docs/docs/reference/src/log/usage.go, pkg/application/error.go, pkg/cli/logger.go, pkg/lambda/error.go, pkg/log/builtin.go, pkg/log/handler.go, pkg/log/handler_iowriter.go, pkg/log/handler_sentry.go, pkg/log/logger.go, pkg/log/logger_context_enforce_test.go, pkg/log/logger_test.go, pkg/log/testdata/config.yml, pkg/metric/logger_handler.go, pkg/test/env/logging.go, pkg/tracing/logging.go, test/httpserver/eof_bind_test.go
We identified a use case where we need finer control over log levels for specific channels to prevent excessive logging while maintaining observability. Previously, the logger configuration allowed defining a set of channels per handler but enforced a single log level for all of them.
This PR introduces per-channel log level configuration
Previously
```yaml
log:
handlers:
main:
type: iowriter
level: debug
channels: [metrics]
formatter: json
timestamp_format: 2006-01-02T15:04:05Z07:00
writer: stdout
``` 
With the change
```yaml
log:
handlers:
main:
type: iowriter
level: debug
channels:
- name: metrics
level: error
formatter: json
timestamp_format: 2006-01-02T15:04:05Z07:00
writer: stdout
```
With this change, the metrics channel can be configured to log only error level messages, even if …
=> log: introduce channel based log levels;

pkg/clock/ticker.go, pkg/clock/ticker_test.go, pkg/clock/timer.go, pkg/clock/timer_test.go, pkg/stream/input_configurable.go
The `Reset` and `Stop` methods of tickers and timers used to be non-threadsafe. However, as this is prone to errors and can easily be fixed, this PR changes them to be safe to call from multiple threads (for example, when using a ticker to implement some basic concurrent rate limiting).
=> clock: make timer and ticker threadsafe

pkg/stream/input_in_memory_test.go, pkg/test/env/container_runner.go
The bridge network allows reachability of containers from the host only on linux. If you try to use that networks ip test containers on mac os or windows (without WSL) are unreachable.
=> feat: make test component containers accessible on osx
