justtrackio/gosoline

pkg/sqs/naming.go
pkg/sqs/queue.go
pkg/sqs/service.go
pkg/sqs/service_test.go
pkg/stream/input_configurable.go
pkg/stream/input_sqs.go
pkg/stream/message.go
pkg/stream/output_sqs.go

added fifo settings to the sqs input

Sqs fifo queue

---

pkg/coffin/coffin.go
pkg/stream/input_sqs.go
pkg/stream/input_sqs_test.go
pkg/stream/message.go
pkg/sub/subscriber.go

handle panics for subscriptions

sub: improve resilience;

---

pkg/blob/store.go
pkg/ddb/metadata_factory.go

- Handle uint fields in ddb model correctly
- Silence error if bucket already exists

Dynamodb uints

---

deployments/terraform/modules/ecr/ecr.tf
deployments/terraform/modules/ecr/variables.tf
deployments/terraform/modules/ecs_container_definition/main.tf
deployments/terraform/modules/ecs_container_definition/output.tf
deployments/terraform/modules/ecs_container_definition/variables.tf
deployments/terraform/modules/sqs/main.tf
deployments/terraform/modules/sqs/output.tf
deployments/terraform/modules/sqs/queue/main.tf
deployments/terraform/modules/sqs/queue/output.tf
deployments/terraform/modules/sqs/queue/variables.tf
deployments/terraform/modules/sqs/variables.tf
deployments/terraform/modules/sqs_sub/main.tf
deployments/terraform/modules/sqs_sub/variables.tf

67-add-generic-terraform-modules

---

deployments/terraform/modules/sqs/main.tf
deployments/terraform/modules/sqs_sub/main.tf

- fix an issue with the terraform source location

fix-terraform-source-location

---

deployments/terraform/modules/ecs_cluster/ec2.tf
deployments/terraform/modules/ecs_cluster/ecs.tf
deployments/terraform/modules/ecs_cluster/iam_ec2.tf
deployments/terraform/modules/ecs_cluster/iam_ecs.tf
deployments/terraform/modules/ecs_cluster/iam_ecs_events.tf
deployments/terraform/modules/ecs_cluster/output.tf
deployments/terraform/modules/ecs_cluster/variables.tf
deployments/terraform/modules/ecs_cluster/vpc.tf

- adding a generic terraform ECS cluster module

add-ecs-cluster-module

---

deployments/terraform/modules/ecs_container_definition/main.tf
deployments/terraform/modules/ecs_container_definition/output.tf
deployments/terraform/modules/ecs_container_definition/variables.tf

- adding new features and stopping the issue with caused the task definition always to recreate

change-ecs-task-definition-terraform-plugin

---

deployments/terraform/modules/ecs_cluster/ec2.tf
deployments/terraform/modules/ecs_cluster_ocean/ec2.tf

- add fluentd as logging driver

adding-new-logging-driver

---

pkg/cfg/config.go
pkg/cfg/config_test.go
pkg/cfg/mocks/Config.go
pkg/cfg/mocks/GosoConf.go
pkg/stream/output_configurable.go

- add configurable fifo settings to sqs output
- add getintslice function to config

sqs output + config

---

pkg/sub/factory.go
pkg/sub/subscriber.go

added the option to configure runner counts for subscriptions

sub: added runner_count config option;

---

pkg/kvstore/batch.go
pkg/kvstore/ddb_test.go
pkg/kvstore/uniq.go
pkg/kvstore/uniq_test.go

kvstore: remove key duplicates for get-batch

---

pkg/apiserver/middleware_logger.go

apiserver: add http request referer to log messages

---

pkg/apiserver/handler.go
pkg/apiserver/middleware_logger.go

Previously we would trigger an error log every time a user send a bad
request which failed to bind. Instead, we now split errors into errors
during binding, during application code and during rendering. If the
error did not occur during application code, the log is demoted to a
warning.

apiserver: only log an error if the error occurred in the application code;

---

pkg/db-repo/repository.go
pkg/ddb/repository.go
pkg/test/component_dynamodb.go
pkg/test/component_elasticsearch.go
pkg/test/component_localstack.go
pkg/test/component_mysql.go
pkg/test/component_redis.go
pkg/test/component_wiremock.go
pkg/test/config.go
pkg/test/test.go

This should enable CIs to also be able to do the integration tests.

Added capability to specify hostnames for services

---

pkg/stream/input_kinsumer.go
pkg/stream/input_kinsumer_factory.go
pkg/stream/kinesis.go
pkg/stream/output_kinesis.go

stream: added kinesis stream auto create;

---

pkg/fixtures/ddb_kv_writer.go
pkg/fixtures/ddb_writer.go
pkg/fixtures/loader.go
pkg/fixtures/mysql_writer.go
pkg/fixtures/writer.go
test/fixtures_dynamodb_test.go
test/fixtures_mysql_test.go

fixtures: removed WriterMetdata property in favour of a factory;

---

pkg/sns/topic.go
pkg/sns/topic_test.go

sns: added executor where missing;

---

pkg/test/component_cloudwatch.go
pkg/test/component_kinesis.go
pkg/test/component_sns_sqs.go
pkg/test/localstack.go
pkg/test/test.go
test/test_configs/config.cloudwatch.test.yml
test/test_configs/config.kinesis.test.yml
test/test_configs/config.sns_sqs.test.yml

test: added localstack health check based on /health route;

---

pkg/ddb/naming.go
pkg/ddb/repository.go
pkg/fixtures/loader.go
pkg/fixtures/purger_dynamodb.go
pkg/fixtures/types.go
pkg/fixtures/writer_ddb.go
pkg/fixtures/writer_ddb_kvstore.go
pkg/fixtures/writer_mysql_orm.go
pkg/fixtures/writer_mysql_plain.go
pkg/fixtures/writer_redis.go
pkg/fixtures/writer_redis_kvstore.go
pkg/kvstore/ddb.go
test/fixtures_dynamodb_test.go

fixtures: added purging for dynamodb and dynamodbKvstore implementation

---

pkg/fixtures/purger_redis.go
pkg/fixtures/writer_redis.go
pkg/fixtures/writer_redis_kvstore.go
pkg/kvstore/redis.go
pkg/redis/mocks/Client.go
pkg/redis/redis_client.go
test/fixtures_redis_test.go

fixtures: added purging for redis and redisKvstore implementation;

---

.gitignore
pkg/stream/output_file.go
pkg/stream/output_file_test.go

stream: fix concurrent write in file output;

---

pkg/db/client.go
pkg/mon/logger_message_encode_handler.go
pkg/mon/logger_message_encode_handler_test.go
pkg/sqs/attributes.go
pkg/sqs/attributes_test.go
pkg/sqs/queue.go
pkg/stream/message.go
pkg/stream/message_encoding.go
pkg/stream/message_encoding_test.go
pkg/stream/output_sqs.go
pkg/stream/output_sqs_test.go
pkg/stream/producer.go
pkg/tracing/message_encode_handler.go
pkg/tracing/message_encode_handler_test.go

sqs, stream: added message deduplication id to forwarded attributes;

---

pkg/apiserver/server.go
pkg/kernel/kernel.go
pkg/mon/metric_daemon.go
pkg/mon/metric_writer_daemon.go

Closes #201 
This MR includes the smaller fixes from !140 without yet introducing the staged kernel.

Smaller kernel fixes separated from !140

---

pkg/apiserver/server.go
pkg/apiserver/server_test.go

For integration testing, we need to be able to start a server on any available port and get the port to communicate with the server (test it).

apiserver: get port from listener;

---

deployments/terraform/modules/sqs/main.tf
deployments/terraform/modules/sqs/queue/main.tf
deployments/terraform/modules/sqs/queue/variables.tf
deployments/terraform/modules/sqs/variables.tf
deployments/terraform/modules/sqs_sub/main.tf

deployments: added fifo capability to tf queue creation

deployments: added fifo capability to tf queue creation

---

pkg/kernel/kernel.go
pkg/kernel/kernel_test.go
pkg/kernel/stage.go

If you had a module with did exit quite fast there was a non-zero chance
of the module terminating before the next goroutine was spawned (it gets
more visible if you put a time.Sleep before spawning new routines, but I
could even trigger it without it). We now wait in the spawned routines for
all routines to have been spawned to avoid this.
Closes #259

kernel: make sure a stage is completely set up after booting;

---

pkg/kvstore/chain.go
pkg/kvstore/chain_test.go
pkg/kvstore/configurable.go
pkg/kvstore/empty.go
pkg/kvstore/in_memory.go
pkg/pubsub/output_kvstore.go
pkg/sub/sub_out_kvstore.go

To reduce cache misses / traffic / costs on the cache elements, I'd like to cache missing values

kvstore: add missing cache config

---

docs/framework/config.all.md
pkg/db-repo/orm.go
pkg/db-repo/repository_test.go
pkg/db/client.go
pkg/db/connection.go
pkg/db/driver_factory.go
pkg/db/metrics.go
pkg/db/migrations.go
pkg/fixtures/purger_mysql.go
pkg/fixtures/writer_mysql_plain.go
pkg/guard/manager_sql.go
pkg/test/env/component_mysql.go
pkg/test/env/components.go
pkg/test/env/factory_mysql.go
test/db_repo_change_history_test.go
test/fixtures_mysql_test.go
test/test_configs/config.db_repo_change_history.test.yml
test/test_configs/config.fixtures_mysql.test.yml

Allow for arbitrary, sql based, databases to be used.
Any database needs to support the sql.Driver interface.

Postgre db

---

go.mod
pkg/cloud/error.go
pkg/coffin/coffin.go
pkg/db/client.go
pkg/ddb/reflect.go
pkg/kernel/kernel.go
pkg/kernel/kernel_test.go
pkg/stream/consumer.go
pkg/stream/consumer_test.go

~~On many linux distributions you get a soft limit of 1024 and a hard limit of 4096 for the number of open files by default. To avoid running into this limit unnecessarily, we automatically increase the soft limit to the hard limit and provide a config option to increase the hard limit, too, if needed (you need to be root for this).~~

various fixes

---

pkg/sqs/mocks/Queue.go
pkg/sqs/queue.go
pkg/stream/input_configurable.go
pkg/stream/input_sns.go
pkg/stream/input_sqs.go
pkg/stream/input_sqs_test.go

default value is 10 when no settings key provided so it should not introduce effects on older applications

sqs: set max number of messages in sqs input via cfg;

---

pkg/parquet/partitioner.go
pkg/parquet/partitioner_test.go

The `flush` function of the `memoryPartitioner` type was operating on a
map without taking the appropriate lock first. This would cause a crash
should the partitioner get a lot of requests (reading from a queue would
be most likely fine, but inventing the elements out of thin air causes
the crash repeatedly).

parquet: lock the memory partitioner before flushing it;

---

pkg/stream/consumer.go

to be able to make decision on sqs visibility timeout config, i've added a duration metric to the stream consumer..

stream: added duration metric to consumer;

---

pkg/coffin/coffin.go
pkg/coffin/coffin_test.go
pkg/coffin/recover.go
pkg/coffin/recover_test.go
pkg/kernel/kernel.go
pkg/kernel/kernel_test.go

to not ignore panics of the last foreground module;

coffin, kernel: added stack trace to recovered errors and changed kernel

---

pkg/apiserver/auth/token_bearer.go

It might be the case that you need the token to decide which TokenBearer
to use. Thus you can now access it as an additional argument in the
TokenBearerProvider type.

apiserver/auth: Added the token as a second argument to the TokenBearerProvider

---

pkg/stream/output_kinesis.go
pkg/stream/output_kinesis_test.go

improve logging for write error cases

stream: cleaned up kinesis output error handling;

---

pkg/ddb/error.go
pkg/ddb/repository.go
pkg/ddb/settings.go

- added custom ddb.TableNotFoundError
- added option to disable tracing via settings

ddb: error and tracing enhancements;

---

deployments/terraform/modules/ecs_cluster_ocean/ec2.tf

deployments: added family tag to ec2 instances;

---

pkg/cli/logger.go

We have to enable the output, otherwise we don't see the log output from the status manager on receiving USR1 as a signal.

cli: enable the output of the CLI logger on signal USR1;

---

go.mod
go.sum

http: update to resty v2.6.0;

---

pkg/mdlsub/subscriber_factory.go

This will fix the Unmarshaling of `mdlsub.Settings`

subscriberApi: fix unmarshling;

---

pkg/apiserver/handler.go

- WithBody and WithContentType are chainable functions for easier usage

create new response with body, status-code, content-type, header

---

pkg/apiserver/sql/query_builder.go

- You can now search for entries in a json array in a mysql db table (type `JSON`) with `MEMBER OF` and `NOT MEMBER OF`

mysql json array query support

---

pkg/apiserver/server.go
pkg/lambda/lambda.go

And also add some channels for api handlers so not everything logs to the kernel channel by default

lambda: added error return to handler factory to account for errors returned from New* methods;

---

pkg/parquet/reader.go

Currently our `parquet.Reader` only provides the capability to read a whole file into a target. In that process all columns of the parquet schema are read and tried to parse into the given schema. As parquet is a column based file format, it is easy for the format to just read specific columns. Therefore it would be nice to have a method to just read some columns and not the whole file.

parquet: add ReadFileColumns function to reader

---

pkg/stream/producer_daemon.go

The producer daemon had an integration test which liked to fail because it was writing a message to the daemon before its `Run` method was called and assigned a value to the ticker used by the daemon. Thus, the `Write` call would try to reset something `nil` and crash. This commit fixes this by ensuring the ticker is only reset after being assigned a value.

stream: added non-nil check before resetting the ticker of the producer daemon;

---

pkg/application/options.go
pkg/application/runners.go
pkg/metric/custom_units.go
pkg/metric/daemon.go
pkg/metric/writer_cw.go
pkg/redis/client.go
pkg/redis/client_test.go
pkg/redis/mocks/Client.go

Changes to allow us to track how many users performed some action (using HyperLogLogs in redis & writing the maximum number as a metric)

Distinct entity metric changes

---

README.md
pkg/cloud/aws/sqs/naming.go
pkg/cloud/aws/sqs/service.go
pkg/cloud/aws/sqs/service_test.go
pkg/test/component_cloudwatch.go
pkg/test/component_dynamodb.go
pkg/test/component_kinesis.go
pkg/test/component_mysql.go
pkg/test/component_redis.go
pkg/test/component_s3.go
pkg/test/component_sns_sqs.go
pkg/test/component_wiremock.go
pkg/test/docker.go
pkg/test/env/factory_localstack.go
pkg/test/env/factory_wiremock.go
pkg/test/localstack.go
pkg/test/mocks.go
pkg/test/mocks_ports.go
test/component_kinesis_test.go
test/component_sns_sqs_test.go
test/fixtures_configurable_kvstore_test.go
test/fixtures_s3_test.go

For the moment this is just a proof that unit tests/integration tests can work flawlessly on Apple Silicon based devices.
I will clean this up once i have free time and will also try to add github actions for the armv8 architecture.

all: poc - apple silicon support;

---

pkg/guard/manager_sql.go
pkg/mdl/model.go
test/guard/fixtures_test.go
test/guard/migrations/01_add_guard_policy.up.sql

Added conditions to the guard manager.

guard: conditions

---

pkg/test/component_cloudwatch.go
pkg/test/component_dynamodb.go
pkg/test/component_kinesis.go
pkg/test/component_mysql.go
pkg/test/component_redis.go
pkg/test/component_s3.go
pkg/test/component_sns_sqs.go
pkg/test/component_wiremock.go
pkg/test/docker.go
pkg/test/env/container_runner.go
pkg/test/mocks.go

fixes #646 and includes #647 for testability

Ensure test component images are pulled prior test execution

---

pkg/cloud/aws/kinesis/kinsumer.go
pkg/stream/consumer_base.go

stream: added consumer names to appctx metadata;

cloud/kinesis: added used streams to appctx metadata

---

pkg/cloud/aws/awsv2.go
pkg/cloud/aws/awsv2_retry.go
pkg/cloud/aws/cloudwatch/client.go
pkg/cloud/aws/dynamodb/client.go
pkg/cloud/aws/ec2/client.go
pkg/cloud/aws/ecs/client.go
pkg/cloud/aws/kinesis/client.go
pkg/cloud/aws/kinesis/kinsumer.go
pkg/cloud/aws/kinesis/metadata_repository.go
pkg/cloud/aws/kinesis/retry.go
pkg/cloud/aws/kinesis/shard_reader.go
pkg/cloud/aws/kinesis/shard_reader_test.go
pkg/cloud/aws/rds/client.go
pkg/cloud/aws/resourcegroupstaggingapi/client.go
pkg/cloud/aws/s3/client.go
pkg/cloud/aws/sns/client.go
pkg/cloud/aws/sqs/client.go
pkg/cloud/aws/ssm/client.go

cloud/aws: added retry options to client config;
cloud/aws/kinesis: added specific retry backoff handling for the ProvisionedThroughputExceededException;

aws and kinesis improvements

---

pkg/cloud/aws/kinesis/record_writer.go
pkg/cloud/aws/kinesis/record_writer_test.go
pkg/mdlsub/config_postprocessor_publisher.go
pkg/stream/consumer_base.go
pkg/stream/output_configurable.go
pkg/stream/output_kinesis.go
pkg/stream/output_tracer.go
pkg/stream/producer_daemon_config_postprocessor.go

cloud/aws/kinesis: added RecordWriter;
stream: using RecordWriter for kinesis output and small improvements;

cloud/aws/kinesis: added RecordWriter

---

pkg/log/fields.go

log: prevent empty log field names (ES dislikes them);

---

pkg/clock/fake_clock.go
pkg/clock/fake_clock_options.go
pkg/cloud/aws/kinesis/kinesis.go
pkg/cloud/aws/kinesis/kinsumer.go
pkg/cloud/aws/kinesis/record_writer.go
pkg/cloud/aws/kinesis/record_writer_test.go
pkg/cloud/aws/kinesis/shard_reader.go
pkg/cloud/aws/kinesis/shard_reader_test.go
pkg/ddb/service.go
pkg/stream/output_kinesis.go

cloud/aws/kinesis:
- Kinsumer creation fails if stream does not exist
- RecordWriter creation fails if stream does not exist
- RecordWriter improvements on failing records
ddb: repostory creation fails if the table does not exist

kinesis and ddb improvements

---

pkg/cloud/aws/kinesis/kinsumer.go
pkg/cloud/aws/kinesis/shard_reader.go
pkg/cloud/aws/kinesis/shard_reader_test.go
pkg/stream/retry_sqs.go

This PR makes the suffix of a consumer retry queue configurable.

configurable consumer retry queue name

---

pkg/cloud/aws/awsv2_middleware_retry.go
pkg/cloud/aws/kinesis/checkpoint.go
pkg/cloud/aws/kinesis/kinsumer.go
pkg/cloud/aws/kinesis/metadata_repository.go
pkg/cloud/aws/kinesis/shard_reader.go
pkg/cloud/aws/kinesis/shard_reader_test.go
pkg/stream/consumer_base.go

Enabled the kinsumer to process records with a configured delay.

kinsumer delay

---

pkg/mdlsub/config_postprocessor_publisher.go
pkg/mdlsub/config_postprocessor_subscriber.go
pkg/mdlsub/subscriber_callback.go
pkg/mdlsub/subscriber_factory.go
pkg/stream/input_configurable.go
pkg/test/suite/testcase_subscriber.go

- made the subscriber capable to handle shared publishers
- added kinesis as input source

mdlsub: subscriber improvements

---

pkg/cloud/aws/awsv2_retry.go
pkg/metric/writer_cw.go

metric: using noop logger for cw metric writer until proper fix is in place

cloud/aws: fixed max attempts retry issue

---

pkg/apiserver/auth/config_google.go
pkg/apiserver/auth/config_google_test.go

To support multiple calling projects, we want to support several google projects as a login source.

apiserver: use list of audiences;

---

pkg/apiserver/middleware_logger.go

If we get hit by a crawler, we often get unexpected query parameters. To avoid generating too many log fields in Kibana, we only add the query parameters as a raw object on successful requests to the log message.

apiserver: don't build a nice object with query parameters for failed requests

---

go.mod
go.sum
pkg/ipinfo/client.go
pkg/limit/chained.go
pkg/limit/fixed_window.go
pkg/limit/fixed_window_ddb.go
pkg/limit/fixed_window_redis.go
pkg/limit/invocation.go
pkg/limit/leaky_bucket.go
pkg/limit/limiter.go
pkg/limit/middleware.go
pkg/limit/middleware_log.go
pkg/limit/middleware_metrics.go

We do not have rate limiting software in gosoline yet. Currently we implement rate limiting only in our internal projects but as the demand grows to having it in multiple project and the code is pretty generic and can we applied in multiple situations, we want to have it in gosoline.

limit: added rate limiting package;

---

pkg/conc/key_lock.go
pkg/conc/key_lock_test.go
pkg/db-repo/change_history_manager.go
pkg/mdl/factory.go
pkg/test/env/components.go
pkg/test/env/container_runner.go

- added some methods to mdl to work with empty values
- fixed KeyLock race condition
- run change history migrations per model in parallel for moderate speedup of local development with remote database
- improved error message for missing external container

added more mdl methods, fixed keylock, small improvements for local development

---

pkg/apiserver/compression.go
pkg/apiserver/server.go
test/apiserver/panic_test.go

Return 500 status code instead of 200;

fix apiserver panic handling;

---

pkg/mapx/struct.go
pkg/mapx/struct_test.go

mapx: it's a bug;

---

.github/workflows/search-index.yml
docs/docsearch-config.json
docs/docusaurus.config.js

This adds a search bar and an action for search reindexing.

Add docs search

---

pkg/appctx/appctx.go
pkg/appctx/container.go
pkg/appctx/metadata.go

Add pkgsite compatible documentation including cross references for the appctx package.

appctx: Add documentation

---

docs/docs/quickstart/http-server/src/write-crud-sql-app/config.dist.yml
docs/docs/quickstart/http-server/src/write-crud-sql-app/migrations/1_initialize_schema.up.sql

This tutorial is out of date due to some Goose changes. Updating the docs.

Update docs for SQL migrations

---

pkg/currency/module.go
pkg/db-repo/change_history_manager.go
pkg/db-repo/change_history_metadata.go
pkg/ddb/metadata.go
pkg/ddb/service.go
pkg/funk/slice.go
pkg/funk/slice_test.go
pkg/httpserver/auth/config_google.go
pkg/httpserver/auth/config_key.go
pkg/httpserver/rpr_handler.go
pkg/redis/client_test.go
pkg/test/env/component_localstack.go
pkg/test/env/components_config_manager.go
pkg/test/suite/options_suite.go
test/db-repo/change_history/schema/change_history_test.go
test/db-repo/change_history/schema/migrations/1_migrations_tables.up.sql

currency: add health check to module;
change-history: drop columns and recreate triggers;
all: update exp/slices to slices;

currency: add health check to module;

---

pkg/test/env/logging.go

Implement multiplexing on test log collection by channel to facilitate quicker log filtering by allowing to easily filter on a single channel (this is a non breaking change)

test env log collection per log channel

---

pkg/stream/output_channel.go
pkg/stream/producer_daemon.go
pkg/test/suite/run.go

This PR fixes using the testing Suite.WithSharedEnvironment in scenarios where there is a producer daemon and more than one test case.

fix: Implement restartability on producer daemon without reset;

---

pkg/currency/module.go
pkg/currency/updater.go

currency: add locking to currency updater

---

pkg/http/client.go

If you want to perform an HTTP request to a user-provided URL, you should not use the default resolver when running inside a cloud setting. Doing so might make it possible to actually send these requests to internal services which are not possible to be resolved from the outside. To avoid this, you can now provide a list of DNS servers like 8.8.8.8 or 1.1.1.1 to use, which can't resolve your internal services.

http: added option to specify the DNS resolvers to use;
